// ===================== 30天主题总览（地图用） =====================
const THEMES = [
  ["姜太公钓鱼", "耐心等待，愿者上钩", "🎣"],
  ["渔夫和金鱼", "知足才能常乐", "🐠"],
  ["鲤鱼跳龙门", "坚持就能跃过龙门", "🐟"],
  ["涸辙之鲋", "及时伸出援手", "🔵"],
  ["网开一面", "宽容留一条生路", "🕸️"],
  ["鱼为什么离不开水", "鳃，鱼儿的呼吸器官", "🐟"],
  ["鱼鳞会说话", "鳞片的年轮记秘密", "🍥"],
  ["鱼钩的学问", "蠕动的钩与饵", "🪝"],
  ["浮漂的悄悄话", "读懂水面上的信号", "🍃"],
  ["钓线打结", "结牢才能挂大风", "🪢"],
  ["潮汐涨落", "大海的呼吸", "🌊"],
  ["淡水鱼和海水鱼", "咸与淡的家", "🐠"],
  ["大马哈鱼回家", "逆流千里的决心", "🐟"],
  ["鳟鱼逆流而上", "迎着困难向上游", "🏔️"],
  ["黑鱼护子", "妈妈的爱最强大", "🖤"],
  ["鲫鱼和鲤鱼", "鱼塘里的好邻居", "🐟"],
  ["鲈鱼公子", "餐桌上的美味朋友", "🐠"],
  ["清道夫和草鱼", "勤快的清洁工", "🌿"],
  ["钓鱼要看天气", "看云识天气", "⛅"],
  ["水边的安全", "安全永远第一", "⚠️"],
  ["放流，钓鱼人的品格", "钓大放小、爱护家园", "🤝"],
  ["钓场公约", "做个讲礼貌的小钓手", "📜"],
  ["鱼会睡觉吗", "睁着眼睛的睡眠", "🌙"],
  ["鱼为什么跃出水面", "好奇的泡泡问题", "💦"],
  ["钓行日记", "记录我的每一次出钓", "📔"],
  ["秤鱼与量尺", "钓鱼人的尺子", "📏"],
  ["鱼线的秘密", "细丝里的大学问", "🎗️"],
  ["渔家谚语", "老祖宗的钓鱼智慧", "🀄"],
  ["我的钓鱼故事", "把30天讲给家人听", "🗣️"],
  ["光荣毕业", "钓手证书颁发仪式", "🎓"],
];

// ===================== 前3天完整课程 =====================
const DAY_DATA = {

  1: {
    title: "姜太公钓鱼", sub: "愿者上钩", emoji: "🎣",
    img: "assets/images/rod.jpg",
    story: [
      { t: "很久以前，姜太公坐在渭水边钓鱼", py: "hěn jiǔ yǐ qián，jiāng tài gōng zuò zài wèi shuǐ biān diào yú" },
      { t: "别人用弯钩，他却用一根直钩", py: "bié rén yòng wān gōu，tā què yòng yī gēn zhí gōu" },
      { t: "直钩不挂饵，还离水三尺高", py: "zhí gōu bù guà ěr，hái lí shuǐ sān chǐ gāo" },
      { t: "别人笑他：这能钓到鱼吗？", py: "bié rén xiào tā：zhè néng diào dào yú ma？" },
      { t: "姜太公说：愿者上钩", py: "jiāng tài gōng shuō：yuàn zhě shàng gōu" },
      { t: "后来周王前来，请他出山治理天下", py: "hòu lái zhōu wáng qián lái，qǐng tā chū shān zhì lǐ tiān xià" },
      { t: "更奇怪的是，他的鱼竿一直举着不动，像松树一样稳", py: "gèng qí guài de shì，tā de yú gān yī zhí jǔ zhe bù dòng，xiàng sōng shù yī yàng wěn" },
      { t: "其实姜太公钓的不是鱼，而是机会和贤才", py: "qí shí jiāng tài gōng diào de bù shì yú，ér shì jī huì hé xián cái" },
    ],
    moral: "沉住气、等时机，好机会会自己找上门。",
    rhymelines: ["直钩钓鱼渭水滨", "姜公公心不慌", "愿者上钩等明君"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "鱼儿", img: "assets/images/koi.jpg" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "河水", img: "assets/images/water.jpg" },
      { char: "石", py: "shí", emoji: "🪨", word: "石头", img: "assets/images/stone.jpg" },
      { char: "竿", py: "gān", emoji: "🎣", word: "鱼竿", img: "assets/images/rod.jpg" },
    ],
    chars: ["鱼", "水", "口", "大"],
    seq: {
      "鱼": "撇 → 横撇 → 竖 → 横折 → 横 → 竖 → 横 → 横",
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "口": "竖 → 横折 → 横",
      "大": "横 → 撇 → 捺",
    },
    speak: [
      { t: "姜太公在渭水边，用直钩钓鱼。", img: "assets/images/rod.jpg" },
      { t: "别人笑他，他一点也不慌。", img: "assets/images/water.jpg" },
      { t: "愿者上钩，好机会自己来。", img: "assets/images/koi.jpg" },
    ],
    quiz: [
      { p: "姜太公钓鱼用的是什么样的钩？", opt: [ {e:"🪝",t:"直钩",r:1}, {e:"🎣",t:"弯钩"}, {e:"📎",t:"U形钩"} ] },
      { p: "姜太公最后等来了谁？", opt: [ {e:"👑",t:"周王",r:1}, {e:"🐟",t:"一条大鱼"}, {e:"🎭",t:"卖鱼的"} ] },
      { p: "这个故事告诉我们什么？", opt: [ {e:"🧘",t:"沉住气等时机",r:1}, {e:"🏃",t:"使劲乱拉竿"}, {e:"😤",t:"发脾气"} ] },
    ],
    craft: '拿一根小线、一块磁铁（或曲别针）当"直钩"，放在装满水的盆边，试试耐心等一小会儿，看看会不会有"愿者"自己来？静下来数心跳，体会等待的感觉（练习专注）。',
    parent: '8岁的孩子正缺"等待"的能力。共读后可以聊：诱惑面前（游戏、零食），能不能也学姜太公"愿者上钩"，不被小小的钩牵着走？',
  },

  2: {
    title: "渔夫和金鱼", sub: "知足才能常乐", emoji: "🐠",
    img: "assets/images/goldfish.jpg",
    story: [
      { t: "一位老渔夫网到一条会说话的金鱼", py: "yī wèi lǎo yú fū wǎng dào yī tiáo huì shuō huà de jīn yú" },
      { t: "金鱼说：放了我，我可以报答你", py: "jīn yú shuō：fàng le wǒ，wǒ kě yǐ bào dá nǐ" },
      { t: "渔夫心善，放回了大海", py: "yú fū xīn shàn，fàng huí le dà hǎi" },
      { t: "可老太太知道后，一次次索要更多", py: "kě lǎo tài tai zhī dào hòu，yī cì cì suǒ yào gèng duō" },
      { t: "要新木盆、要大房子、要当女王……", py: "yào xīn mù pén、yào dà fáng zi、yào dāng nǚ wáng……" },
      { t: "贪心的愿望一个个来，又一个个消失", py: "tān xīn de yuàn wàng yī gè gè lái，yòu yī gè gè xiāo shī" },
      { t: "最后，海水起了波涛，一切都回到了从前", py: "zuì hòu，hǎi shuǐ qǐ le bō tāo，yī qiè dōu huí dào le cóng qián" },
      { t: "金鱼不再出现，老渔夫又过回平静的日子", py: "jīn yú bù zài chū xiàn，lǎo yú fū yòu guò huí píng jìng de rì zi" },
    ],
    moral: "欲望没有尽头，懂得知足，心里才装得下快乐。",
    rhymelines: ["渔翁撒网钓海鱼", "金鱼报恩来帮忙", "贪心不足篮子空"],
    vocab: [
      { char: "金", py: "jīn", emoji: "🪙", word: "金色", img: "assets/images/gold.jpg" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "金鱼", img: "assets/images/goldfish.jpg" },
      { char: "大", py: "dà", emoji: "🐻", word: "大房子" },
      { char: "小", py: "xiǎo", emoji: "🐜", word: "小小的" },
    ],
    chars: ["大", "小", "人", "日"],
    seq: {
      "大": "横 → 撇 → 捺",
      "小": "竖钩 → 撇 → 点",
      "人": "撇 → 捺",
      "日": "竖 → 横折 → 横 → 横 → 横",
    },
    speak: [
      { t: "老渔夫心善，把金鱼放回大海。", img: "assets/images/goldfish.jpg" },
      { t: "知足的人，心里总是满满当当。", img: "assets/images/gold.jpg" },
      { t: "小愿望实现就够啦，感恩每一天。", img: "assets/images/water.jpg" },
    ],
    quiz: [
      { p: "金鱼说，放了自己可以做什么？", opt: [ {e:"🎁",t:"报答你",r:1}, {e:"🏊",t:"游给你看"}, {e:"🎨",t:"变魔术"} ] },
      { p: "老太太不停向金鱼要什么？", opt: [ {e:"🏠",t:"更多东西",r:1}, {e:"🙏",t:"感谢"}, {e:"😴",t:"好好休息"} ] },
      { p: "这个故事主要劝我们？", opt: [ {e:"😊",t:"知足常乐",r:1}, {e:"🤑",t:"一直要更多"}, {e:"😴",t:"躺平不动"} ] },
    ],
    craft: '找一个小罐子，让孩子把自己"最想要的东西"画在小纸条上放进去，每天只拿出一张去实现它；一周下来聊聊：真正让你快乐的是哪一样？（练习珍惜与感恩）',
    parent: '可以和孩子聊"想要"和"需要"的区别。当他想要新款玩具时，问一句：这是需要的还是想要的？帮助孩子建立延迟满足与感恩意识。',
  },

  3: {
    title: "鲤鱼跳龙门", sub: "坚持就能跃过龙门", emoji: "🐟",
    img: "assets/images/koi.jpg",
    story: [
      { t: "在黄河边上，有一座高高的龙门", py: "zài huáng hé biān shàng，yǒu yī zuò gāo gāo de lóng mén" },
      { t: "传说只要跳过龙门，鲤鱼就能变成龙", py: "chuán shuō zhǐ yào tiào guò lóng mén，lǐ yú jiù néng biàn chéng lóng" },
      { t: "千万条鲤鱼来试，大多撞得头破血流", py: "qiān wàn tiáo lǐ yú lái shì，dà duō zhuàng dé tóu pò xuè liú" },
      { t: "有一条小鲤鱼，白天练，晚上也练", py: "yǒu yī tiáo xiǎo lǐ yú，bái tiān liàn，wǎn shàng yě liàn" },
      { t: "它一次次跃起，又一次次落下", py: "tā yī cì cì yuè qǐ，yòu yī cì cì luò xià" },
      { t: "终于，小鲤鱼在第五十七次跳过了龙门", py: "zhōng yú，xiǎo lǐ yú zài dì wǔ shí qī cì tiào guò le lóng mén" },
      { t: "天上的白云为它加油，水里的同伴为它鼓劲", py: "tiān shàng de bái yún wèi tā jiā yóu，shuǐ lǐ de tóng bàn wèi tā gǔ jìn" },
      { t: "跳过龙门的瞬间，小鲤鱼变成了一条金龙", py: "tiào guò lóng mén de shùn jiān，xiǎo lǐ yú biàn chéng le yī tiáo jīn lóng" },
    ],
    moral: "一次不够就一百次，坚持再坚持，小鲤鱼也能变成龙。",
    rhymelines: ["小鲤鱼，跳龙门", "一次不行练十次", "跳过去，变成龙"],
    vocab: [
      { char: "门", py: "mén", emoji: "🚪", word: "龙门", img: "assets/images/door.jpg" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "河水", img: "assets/images/water.jpg" },
      { char: "龙", py: "lóng", emoji: "🐉", word: "神龙" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "鲤鱼", img: "assets/images/koi.jpg" },
    ],
    chars: ["门", "水", "山", "云"],
    seq: {
      "门": "点 → 竖 → 横折钩",
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "山": "竖 → 竖折 → 竖",
      "云": "横 → 横 → 撇折 → 点",
    },
    speak: [
      { t: "小鲤鱼一次次跳，从不放弃。", img: "assets/images/koi.jpg" },
      { t: "坚持努力，就能跃过自己的龙门。", img: "assets/images/door.jpg" },
      { t: "一次不行，那就再来一次！", img: "assets/images/water.jpg" },
    ],
    quiz: [
      { p: "鲤鱼跳过龙门会变成什么？", opt: [ {e:"🐉",t:"一条龙",r:1}, {e:"🐟",t:"大鲨鱼"}, {e:"🦅",t:"鹰"} ] },
      { p: "小鲤鱼是怎么成功的？", opt: [ {e:"🏋️",t:"一次次坚持",r:1}, {e:"🪂",t:"等风把它吹上去"}, {e:"🧜",t:"求仙子帮忙"} ] },
      { p: "小鲤鱼跳了多少次才成功？", opt: [ {e:"5️⃣7️⃣",t:"五十七次",r:1}, {e:"1️⃣",t:"一次"}, {e:"1️⃣0️⃣0️⃣",t:"一百次"} ] },
    ],
    craft: '在地上画一条"龙门"，用双脚跳过去，记录每次失败的原因：是起跳太早？膝盖没弯？调整三次再挑战，体验"练习带来进步"（锻炼身体与抗挫折）。',
    parent: '孩子学跳绳、游泳、写字遇到瓶颈时，把这事讲成"鲤鱼跳龙门"。记住过程比结果重要，肯定它的每一次尝试，而不是只夸最后一次成功。',
  },

  4: {
    title: "涸辙之鲋", sub: "及时伸出援手", emoji: "🔵",
    story: [
      { t: "庄子在那条快干涸的车辙里，看到一条小鱼", py: "zhuāng zǐ zài nà tiáo kuài gān hé de chē zhé lǐ，kàn dào yī tiáo xiǎo yú" },
      { t: "小鱼说：请你舀一点水来救救我吧", py: "xiǎo yú shuō：qǐng nǐ yǎo yī diǎn shuǐ lái jiù jiù wǒ ba" },
      { t: "庄子说：好，我去找大江大河的水", py: "zhuāng zǐ shuō：hǎo，wǒ qù zhǎo dà jiāng dà hé de shuǐ" },
      { t: "小鱼哭了：等你的水一来，我早干死了", py: "xiǎo yú kū le：děng nǐ de shuǐ yī lái，wǒ zǎo gān sǐ le" },
      { t: "救人要救急，而不是空许诺", py: "jiù rén yào jiù jí，ér bù shì kōng xǔ nuò" },
      { t: "水不在多，在于及时；爱不在远，在于眼前", py: "shuǐ bù zài duō，zài yú jí shí；ài bù zài yuǎn，zài yú yǎn qián" },
      { t: "庄子听了小鱼的话，羞愧地低下了头", py: "zhuāng zǐ tīng le xiǎo yú de huà，xiū kuì dì dī xià le tóu" },
      { t: "所以帮助别人不能只说不做，行动比承诺重要", py: "suǒ yǐ bāng zhù bié rén bù néng zhǐ shuō bù zuò，xíng dòng bǐ chéng nuò zhòng yào" },
    ],
    moral: '帮助别人要趁早、要实在，一句"以后再说"救不了眼前的人。',
    rhymelines: ["车辙小鱼快干涸", "庄子答应去取水", "远水难救近渴鱼"],
    vocab: [
      { char: "水", py: "shuǐ", emoji: "💧", word: "井水" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "小鱼" },
      { char: "大", py: "dà", emoji: "🐻", word: "大江" },
      { char: "干", py: "gān", emoji: "🏜️", word: "干涸" },
    ],
    chars: ["水", "山", "人", "田"],
    seq: {
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "山": "竖 → 竖折 → 竖",
      "人": "撇 → 捺",
      "田": "竖 → 横折 → 横 → 竖 → 横",
    },
    speak: ["救人要趁早，别等水都等不来。", "说一句关心的话，也要立刻去做。", "身边有人需要帮忙，就伸一把手。"],
    quiz: [
      { p: "小鱼在什么地方喊救命？", opt: [ {e:"🛞",t:"干涸的车辙",r:1}, {e:"🌊",t:"大海里"}, {e:"🛁",t:"浴缸里"} ] },
      { p: "庄子说要到哪里去取水？", opt: [ {e:"🌊",t:"大江大河",r:1}, {e:"🚰",t:"水龙头"}, {e:"⛲",t:"喷泉"} ] },
      { p: "这则寓言告诉我们？", opt: [ {e:"🤝",t:"帮助要及时",r:1}, {e:"⏰",t:"可以慢慢等"}, {e:"🙈",t:"装作没看见"} ] },
    ],
    craft: '接两盆水：一盆放一张纸巾（快速吸水），一盆放一杯颜料（要"等"才溶）。比一比，哪些帮助立刻见效？学做"及时雨"（科学小观察）。',
    parent: '这则故事打击"遥远承诺"。和孩子约定：答应别人的事要当天做；平时也可以让孩子帮忙做小事（倒水、擦桌），建立"谢谢"的互动。',
  },

  5: {
    title: "网开一面", sub: "宽容留一条生路", emoji: "🕸️",
    story: [
      { t: "商汤外出，看到猎人四面张网捕鸟", py: "shāng tāng wài chū，kàn dào liè rén sì miàn zhāng wǎng bǔ niǎo" },
      { t: "商汤说：这样四面八方都堵住了", py: "shāng tāng shuō：zhè yàng sì miàn bā fāng dōu dǔ zhù le" },
      { t: "他让猎人撤去三面网，只留一面", py: "tā ràng liè rén chè qù sān miàn wǎng，zhǐ liú yī miàn" },
      { t: "他说：愿意往哪飞，就往哪飞吧", py: "tā shuō：yuàn yì wǎng nǎ fēi，jiù wǎng nǎ fēi ba" },
      { t: '从此这个故事流传开来，成了"网开一面"', py: "cóng cǐ zhè gè gù shì liú chuán kāi lái，chéng le wǎng kāi yī miàn" },
      { t: "鸟儿们扑棱棱飞起来，天空一下子热闹了", py: "niǎo ér men pū lēng lēng fēi qǐ lái，tiān kōng yī xià zi rè nào le" },
      { t: "留条生路给别人，就是给自己留福气", py: "liú tiáo shēng lù gěi bié rén，jiù shì gěi zì jǐ liú fú qì" },
      { t: "给别人留一条路，也给自己留一片天", py: "gěi bié rén liú yī tiáo lù，yě gěi zì jǐ liú yī piàn tiān" },
    ],
    moral: "得理也让人三分，给别人留条路，路才会越来越宽。",
    rhymelines: ["猎人张网四面包", "商汤网开留一面", "留口生路天地宽"],
    vocab: [
      { char: "网", py: "wǎng", emoji: "🕸️", word: "渔网" },
      { char: "人", py: "rén", emoji: "🧍", word: "猎人" },
      { char: "鸟", py: "niǎo", emoji: "🐦", word: "飞鸟" },
      { char: "面", py: "miàn", emoji: "🌀", word: "一面" },
    ],
    chars: ["口", "人", "木", "心"],
    seq: {
      "口": "竖 → 横折 → 横",
      "人": "撇 → 捺",
      "木": "横 → 竖 → 撇 → 捺",
      "心": "点 → 斜钩 → 点 → 点",
    },
    speak: ["得理也让人三分，心里更安。", "给别人留条路，路会越走越宽。", "宽容不是软弱，是海阔天空。"],
    quiz: [
      { p: "商汤让猎人去掉了几面网？", opt: [ {e:"3️⃣",t:"三面",r:1}, {e:"1️⃣",t:"一面"}, {e:"4️⃣",t:"四面"} ] },
      { p: '"网开一面"现在常常形容什么？', opt: [ {e:"🤲",t:"宽容给人机会",r:1}, {e:"🕸️",t:"多撒网抓鱼"}, {e:"🚧",t:"堵住所有路口"} ] },
      { p: "这个故事里的主角是？", opt: [ {e:"👑",t:"商汤",r:1}, {e:"🐦",t:"一只鸟"}, {e:"🕷️",t:"蜘蛛"} ] },
    ],
    craft: '用几根毛线编一个"密码网"：想一个自己最近没做好的事，把它当成"钻过去的那面网"，想想怎么做才更好（练习自省与和解）。',
    parent: '孩子和小伙伴闹别扭后，引导他说出对方的"一面网开"。宽容不是一味让，而是有理有据地原谅。',
  },

  6: {
    title: "鱼为什么离不开水", sub: "鳃，鱼儿的呼吸器官", emoji: "🐟",
    story: [
      { t: "小鱼问妈妈：我们为什么离不开水？", py: "xiǎo yú wèn mā ma：wǒ men wèi shén me lí bù kāi shuǐ？" },
      { t: "妈妈指着两侧的腮盖说：靠它呼吸", py: "mā ma zhǐ zhe liǎng cè de sāi gài shuō：kào tā hū xī" },
      { t: "水流过鳃丝，氧就进了血液", py: "shuǐ liú guò sāi sī，yǎng jiù jìn le xuè yè" },
      { t: "离开水，鳃丝粘在一起，没法换气", py: "lí kāi shuǐ，sāi sī zhān zài yī qǐ，méi fǎ huàn qì" },
      { t: "所以鱼儿的家，是那流动的水", py: "suǒ yǐ yú ér de jiā，shì nà liú dòng de shuǐ" },
      { t: "小鱼明白了：水的怀抱，就是它温暖的家", py: "xiǎo yú míng bai le：shuǐ de huái bào，jiù shì tā wēn nuǎn de jiā" },
      { t: "妈妈又说：你也要找到让自己舒服的方式哦", py: "mā ma yòu shuō：nǐ yě yào zhǎo dào ràng zì jǐ shū fu de fāng shì o" },
      { t: "每种生命，都有属于自己的呼吸和节奏", py: "měi zhǒng shēng mìng，dōu yǒu shǔ yú zì jǐ de hū xī hé jié zòu" },
    ],
    moral: '每个人都有自己"呼吸"的方式，尊重各自的成长环境。',
    rhymelines: ["宝宝住在小池塘", "鳃儿呼吸时时帮", "离开水儿就受伤"],
    vocab: [
      { char: "水", py: "shuǐ", emoji: "💧", word: "水花" },
      { char: "脸", py: "liǎn", emoji: "👦", word: "小脸" },
      { char: "家", py: "jiā", emoji: "🏠", word: "老家" },
      { char: "头", py: "tóu", emoji: "🐟", word: "鱼头" },
    ],
    chars: ["口", "木", "日", "月"],
    seq: {
      "口": "竖 → 横折 → 横",
      "木": "横 → 竖 → 撇 → 捺",
      "日": "竖 → 横折 → 横 → 横 → 横",
      "月": "撇 → 横折钩 → 横 → 横",
    },
    speak: ["鱼儿的家，是流动的水。", "鳃是鱼儿的呼吸机器。", "尊重每一个生命自己的活法。"],
    quiz: [
      { p: "鱼儿靠什么呼吸？", opt: [ {e:"🫁",t:"鳃",r:1}, {e:"🫀",t:"心脏"}, {e:"👃",t:"鼻子"} ] },
      { p: "鱼离开水为什么没法呼吸？", opt: [ {e:"🩹",t:"鳃丝粘在一起",r:1}, {e:"🦵",t:"没有腿走路"}, {e:"👀",t:"看不清东西"} ] },
      { p: "鱼儿的家是？", opt: [ {e:"💧",t:"流动的水",r:1}, {e:"🏝️",t:"沙滩"}, {e:"🌲",t:"树林"} ] },
    ],
    craft: '找一个小脸盆装满水，把小手放进去再合拢又张开，感受水的"流动"；再用保鲜膜包一下鼻口几秒钟体会缺氧的感觉（注意安全、只玩几秒）。（感官体验）',
    parent: "带孩子养一条小金鱼观察腮盖一开一合，再聊聊可不可以养在鱼缸里不换水？顺带讲氧气与换水的常识。",
  },

  7: {
    title: "鱼鳞会说话", sub: "鳞片的年轮记秘密", emoji: "🍥",
    story: [
      { t: "爷爷给小明一片大鱼鳞，让他对着光看", py: "yé ye gěi xiǎo míng yī piàn dà yú lín，ràng tā duì zhe guāng kàn" },
      { t: "鳞片上有一圈一圈的细纹", py: "lín piàn shàng yǒu yī quān yī quān de xì wén" },
      { t: "爷爷说：这些圆圈像树的年轮", py: "yé ye shuō：zhè xiē yuán quān xiàng shù de nián lún" },
      { t: "一圈就是一岁，春宽夏窄", py: "yī quān jiù shì yī suì，chūn kuān xià zhǎi" },
      { t: "小明数了数：这条鱼已经三岁啦", py: "xiǎo míng shǔ le shǔ：zhè tiáo yú yǐ jīng sān suì la" },
      { t: "年轮越深，说明它经历过很多个春夏秋冬", py: "nián lún yuè shēn，shuō míng tā jīng lì guò hěn duō gè chūn xià qiū dōng" },
      { t: "鱼鳞上的秘密，就是大自然写下的日记本", py: "yú lín shàng de mì mì，jiù shì dà zì rán xiě xià de rì jì běn" },
      { t: "每一圈都记录着它游过的水和吃过的食", py: "měi yī quān dōu jì lù zhe tā yóu guò de shuǐ hé chī guò de shí" },
    ],
    moral: "做个爱观察的人，每个小细节里都藏着大学问。",
    rhymelines: ["一片鱼鳞小上头", "一圈细纹是一岁", "边看边数不出错"],
    vocab: [
      { char: "鳞", py: "lín", emoji: "🍥", word: "鳞片" },
      { char: "圈", py: "quān", emoji: "⭕", word: "圆圈" },
      { char: "年", py: "nián", emoji: "📅", word: "年轮" },
      { char: "数", py: "shù", emoji: "🔢", word: "数数" },
    ],
    chars: ["年", "上", "下", "十"],
    seq: {
      "年": "撇 → 横 → 横 → 竖 → 横 → 竖",
      "上": "竖 → 横",
      "下": "横 → 竖 → 点",
      "十": "横 → 竖",
    },
    speak: ["鱼鳞上的圆圈，一圈就是一岁。", "爱观察的孩子，看得见小秘密。", "科学藏在生活里，天天都有新发现。"],
    quiz: [
      { p: "鱼鳞上的细纹像什么？", opt: [ {e:"🌳",t:"树的年轮",r:1}, {e:"🌈",t:"彩虹"}, {e:"🌀",t:"漩涡"} ] },
      { p: "一圈细纹代表多大？", opt: [ {e:"1️⃣",t:"一岁",r:1}, {e:"1️⃣0️⃣",t:"十岁"}, {e:"1️⃣0️⃣0️⃣",t:"一百岁"} ] },
      { p: "小明数出这条鱼几岁了？", opt: [ {e:"3️⃣",t:"三岁",r:1}, {e:"5️⃣",t:"五岁"}, {e:"8️⃣",t:"八岁"} ] },
    ],
    craft: "用放大镜观察一片真正的鱼鳞或一枚硬币上的花纹，把看到的圆圈画下来，数一数、比一比，就像小科学家做记录（培养观察与记录习惯）。",
    parent: '引导孩子把观察结果讲出来，可制成一本"我的发现小书"。观察力是写作和科学的共同引擎。',
  },

  8: {
    title: "鱼钩的学问", sub: "蠕动的钩与饵", emoji: "🪝",
    story: [
      { t: "小齐第一次拿鱼钩，妈妈教他看钩型", py: "xiǎo qí dì yī cì ná yú gōu，mā ma jiāo tā kàn gōu xíng" },
      { t: "小钩钓小鱼，大钩钓大鱼", py: "xiǎo gōu diào xiǎo yú，dà gōu diào dà yú" },
      { t: "钩尖要锋利，倒刺要结实", py: "gōu jiān yào fēng lì，dào cì yào jiē shi" },
      { t: "穿饵也有讲究，不能露出钩尖", py: "chuān ěr yě yǒu jiǎng jiu，bù néng lù chū gōu jiān" },
      { t: "小齐感叹：小小鱼钩，藏着的是专注", py: "xiǎo qí gǎn tàn：xiǎo xiǎo yú gōu，cáng zhe de shì zhuān zhù" },
      { t: "他还学会了：用完的鱼钩要轻轻收好，不伤人不乱丢", py: "tā hái xué huì le：yòng wán de yú gōu yào qīng qīng shōu hǎo，bù shāng rén bù luàn diū" },
      { t: "每一次穿饵，都像在做一件了不起的小事", py: "měi yī cì chuān ěr，dōu xiàng zài zuò yī jiàn liǎo bù qǐ de xiǎo shì" },
      { t: "妈妈摸摸他的头说：细心的小手最棒", py: "mā ma mō mō tā de tóu shuō：xì xīn de xiǎo shǒu zuì bàng" },
    ],
    moral: "把一件小事做到细致，就是了不起的本领。",
    rhymelines: ["小钩钓小鱼", "大钩钓大鱼", "穿饵别露尖"],
    vocab: [
      { char: "钩", py: "gōu", emoji: "🪝", word: "鱼钩" },
      { char: "尖", py: "jiān", emoji: "🔺", word: "锋利" },
      { char: "小", py: "xiǎo", emoji: "🐜", word: "小心" },
      { char: "手", py: "shǒu", emoji: "✋", word: "小手" },
    ],
    chars: ["手", "小", "刀", "力"],
    seq: {
      "手": "撇 → 横 → 横 → 竖钩",
      "小": "竖钩 → 撇 → 点",
      "刀": "横折钩 → 撇",
      "力": "横折钩 → 撇",
    },
    speak: ["小钩钓小鱼，大钩钓大鱼。", "穿饵要用心，钩尖不露头。", "专注做好小事，就是真本事。"],
    quiz: [
      { p: "钩尖要保持什么？", opt: [ {e:"🔪",t:"锋利",r:1}, {e:"🥴",t:"钝钝的"}, {e:"🌟",t:"发光的"} ] },
      { p: "穿饵时要注意什么？", opt: [ {e:"🙈",t:"不露出钩尖",r:1}, {e:"🪄",t:"越多越好"}, {e:"😴",t:"随便穿"} ] },
      { p: "挑选鱼钩要看鱼的什么？", opt: [ {e:"🐟",t:"大小",r:1}, {e:"🎨",t:"颜色"}, {e:"🎵",t:"声音"} ] },
    ],
    craft: '家里找一枚曲别针弯成"钩"，在纸上练习"穿饵"（用粘土小球当饵），比比谁穿得又快又不露尖（手部精细动作）。',
    parent: '强调安全：小朋友绝不自己用手指试钩尖；穿饵最好由大人示范。也可用来讲"细节决定成败"。',
  },

  9: {
    title: "浮漂的悄悄话", sub: "读懂水面上的信号", emoji: "🍃",
    story: [
      { t: "浮漂漂在水面上，一上一下", py: "fú piāo piāo zài shuǐ miàn shàng，yī shàng yī xià" },
      { t: '它像一条小小的"电报线"', py: "tā xiàng yī tiáo xiǎo xiǎo de diàn bào xiàn" },
      { t: "轻轻点头：是不是鱼在试探鱼饵", py: "qīng qīng diǎn tóu：shì bù shì yú zài shì tàn yú ěr" },
      { t: "猛地没入水中：有鱼咬钩啦", py: "měng de mò rù shuǐ zhōng：yǒu yú yǎo gōu la" },
      { t: '看懂浮漂的"悄悄话"，上鱼就有把握', py: "kàn dǒng fú piāo de qiāo qiāo huà，shàng yú jiù yǒu bǎ wò" },
      { t: "钓手叔叔从不说话，只静静看它的表情", py: "diào shǒu shū shu cóng bù shuō huà，zhǐ jìng jìng kàn tā de biǎo qíng" },
      { t: "有时浮漂轻轻晃动，比手机的消息还重要", py: "yǒu shí fú piāo qīng qīng huàng dòng，bǐ shǒu jī de xiāo xi hái zhòng yào" },
      { t: "眼睛盯着水面，心里想着鱼的事", py: "yǎn jīng dīng zhe shuǐ miàn，xīn lǐ xiǎng zhe yú de shì" },
      { t: "学会等待，是当钓手的第一课", py: "xué huì děng dài，shì dāng diào shǒu de dì yī kè" },
    ],
    moral: '学会观察信号、听懂"没说出来"的话，是成长的大本事。',
    rhymelines: ["小浮漂，立水中央", "点头顿口都是话", "看懂它，鱼儿钓上来"],
    vocab: [
      { char: "浮", py: "fú", emoji: "🍃", word: "浮漂" },
      { char: "上", py: "shàng", emoji: "⬆️", word: "上面" },
      { char: "下", py: "xià", emoji: "⬇️", word: "下面" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水面" },
    ],
    chars: ["上", "下", "日", "月"],
    seq: {
      "上": "竖 → 横",
      "下": "横 → 竖 → 点",
      "日": "竖 → 横折 → 横 → 横 → 横",
      "月": "撇 → 横折钩 → 横 → 横",
    },
    speak: ["浮漂点头，是鱼在试探。", "浮漂猛沉，是有鱼咬钩啦。", "会观察信号，收获就不会差。"],
    quiz: [
      { p: "浮漂轻轻点头表示什么？", opt: [ {e:"🐟",t:"鱼在试探饵",r:1}, {e:"🎣",t:"竿要断了"}, {e:"🌧️",t:"要下雨"} ] },
      { p: "浮漂猛地没入水中表示什么？", opt: [ {e:"🦷",t:"鱼咬钩了",r:1}, {e:"🪨",t:"挂到石头"}, {e:"💨",t:"起风了"} ] },
      { p: "看懂浮漂信号靠什么？", opt: [ {e:"👀",t:"细心观察",r:1}, {e:"💤",t:"打瞌睡"}, {e:"📢",t:"大声说话"} ] },
    ],
    craft: '用一个小矿泉水瓶当"浮漂"，在水盆里放轻、放重物，看它上升下沉的变化，练习"信号"的观察（物理小实验）。',
    parent: '把"浮漂"类比成别人的表情和语气：孩子学看人脸色不是讨好，而是学会共情——听懂没说出口的话。',
  },

  10: {
    title: "钓线打结", sub: "结牢才能挂大风", emoji: "🪢",
    story: [
      { t: '教练教小禾打一个"连接结"', py: "jiào liàn jiāo xiǎo hé dǎ yī gè lián jiē jié" },
      { t: "先绕三圈，再从圈里穿过", py: "xiān rào sān quān，zài cóng quān lǐ chuān guò" },
      { t: "轻轻一拉，结就牢住了", py: "qīng qīng yī lā，jié jiù láo zhù le" },
      { t: "小禾以为很简单，却老是松掉", py: "xiǎo hé yǐ wéi hěn jiǎn dān，què lǎo shì sōng diào" },
      { t: "教练说：结打不牢，大鱼一挣就断", py: "jiào liàn shuō：jié dǎ bù láo，dà yú yī zhèng jiù duàn" },
      { t: "小禾用心练了二十遍，终于成功了", py: "xiǎo hé yòng xīn liàn le èr shí biàn，zhōng yú chéng gōng le" },
      { t: "绕线、穿圈、拉紧，每一步都不能马虎", py: "rào xiàn、chuān quān、lā jǐn，měi yī bù dōu bù néng mǎ hu" },
      { t: "她看着手指上磨出的红印，反而更有干劲", py: "tā kàn zhe shǒu zhǐ shàng mó chū de hóng yìn，fǎn ér gèng yǒu gàn jìn" },
      { t: "打好结的那一刻，小禾开心得蹦了起来", py: "dǎ hǎo jié de nà yī kè，xiǎo hé kāi xīn dé bèng le qǐ lái" },
    ],
    moral: "基本功不牢，关键时刻就掉链子。把小事练熟，才有临场的大本事。",
    rhymelines: ["绕三圈，穿一穿", "轻轻拉，结才牢", "基本功，练到老"],
    vocab: [
      { char: "线", py: "xiàn", emoji: "🪢", word: "钓线" },
      { char: "结", py: "jié", emoji: "🎀", word: "打结" },
      { char: "大", py: "dà", emoji: "🐻", word: "大风" },
      { char: "力", py: "lì", emoji: "💪", word: "用力" },
    ],
    chars: ["力", "上", "下", "八"],
    seq: {
      "力": "横折钩 → 撇",
      "上": "竖 → 横",
      "下": "横 → 竖 → 点",
      "八": "撇 → 捺",
    },
    speak: ["结打不牢，大鱼一挣扎就断。", "把小事练熟，才有真本事。", "基本功要天天练，心急吃不了热豆腐。"],
    quiz: [
      { p: "连接结要先绕几圈？", opt: [ {e:"3️⃣",t:"三圈",r:1}, {e:"1️⃣",t:"一圈"}, {e:"9️⃣",t:"九圈"} ] },
      { p: "结打不牢，大鱼会怎样？", opt: [ {e:"💥",t:"一挣就断",r:1}, {e:"🐢",t:"乖乖不动"}, {e:"🎶",t:"唱歌"} ] },
      { p: "小禾最后是怎么学会的？", opt: [ {e:"🧗",t:"用心练二十遍",r:1}, {e:"👾",t:"变魔法"}, {e:"🦄",t:"运气好"} ] },
    ],
    craft: "用鞋带练习三种结：平结、八字结、双套结，看哪种最牢；再学系自己的鞋带蝴蝶结（生活技能练习）。",
    parent: '让孩子每天练习一件"小基本功"（系鞋带、叠被子），坚持一周，体会"熟能生巧"。',
  },

  11: {
    title: "潮汐涨落", sub: "大海的呼吸", emoji: "🌊",
    story: [
      { t: "大海每天早上涨潮，傍晚又退潮", py: "dà hǎi měi tiān zǎo shàng zhǎng cháo，bàng wǎn yòu tuì cháo" },
      { t: "涨潮时，海水涌上沙滩", py: "zhǎng cháo shí，hǎi shuǐ yǒng shàng shā tān" },
      { t: "退潮时，贝壳和海菜留在滩上", py: "tuì cháo shí，bèi ké hé hǎi cài liú zài tān shàng" },
      { t: "是谁在拉着大海一呼一吸？", py: "shì shuí zài lā zhe dà hǎi yī hū yī xī？" },
      { t: "悄悄话：是月亮婆婆在帮忙", py: "qiāo qiāo huà：shì yuè liang pó po zài bāng máng" },
      { t: "潮起潮落，是大海每天的歌", py: "cháo qǐ cháo luò，shì dà hǎi měi tiān de gē" },
      { t: "太阳也赶来帮忙，和月亮一起牵着大海的手", py: "tài yáng yě gǎn lái bāng máng，hé yuè liang yī qǐ qiān zhe dà hǎi de shǒu" },
      { t: "看潮的孩子知道了：世界其实一刻也不停", py: "kàn cháo de hái zi zhī dào le：shì jiè qí shí yī kè yě bù tíng" },
      { t: "大自然有自己的钟表，准时又温柔", py: "dà zì rán yǒu zì jǐ de zhōng biǎo，zhǔn shí yòu wēn róu" },
    ],
    moral: '大自然按着规律运转，学会观察规律，心里就有一张"时刻表"。',
    rhymelines: ["大海早晨涨涨潮", "傍晚退潮露沙滩", "月亮婆婆在帮忙"],
    vocab: [
      { char: "海", py: "hǎi", emoji: "🌊", word: "大海" },
      { char: "潮", py: "cháo", emoji: "🫧", word: "潮水" },
      { char: "月", py: "yuè", emoji: "🌙", word: "月亮" },
      { char: "沙", py: "shā", emoji: "🏖️", word: "沙滩" },
    ],
    chars: ["月", "日", "水", "山"],
    seq: {
      "月": "撇 → 横折钩 → 横 → 横",
      "日": "竖 → 横折 → 横 → 横 → 横",
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "山": "竖 → 竖折 → 竖",
    },
    speak: ["大海在呼吸，潮起又潮落。", "是月亮婆婆在帮大海换气。", "跟着规律走，心里有张时刻表。"],
    quiz: [
      { p: '潮汐是谁在"帮忙"？', opt: [ {e:"🌙",t:"月亮",r:1}, {e:"☀️",t:"太阳镜"}, {e:"🌪️",t:"龙卷风"} ] },
      { p: "退潮后沙滩上常见什么？", opt: [ {e:"🐚",t:"贝壳海菜",r:1}, {e:"🍔",t:"汉堡"}, {e:"🎁",t:"礼物盒"} ] },
      { p: "潮起潮落很有什么？", opt: [ {e:"🎼",t:"规律",r:1}, {e:"🎲",t:"随机性"}, {e:"🃏",t:"运气"} ] },
    ],
    craft: '用一个大盆和一摞书模拟海滩：舀一瓢水"涨潮"、倒掉"退潮"，把乐高小鱼放在滩上，观察每次"退潮"留下什么（潮汐模拟实验）。',
    parent: '带孩子查一查明天的潮汐时刻表（APP/日历），实地去码头看一次涨潮退潮，把"规律"变成看得见的记忆。',
  },

  12: {
    title: "淡水鱼和海水鱼", sub: "咸与淡的家", emoji: "🐠",
    story: [
      { t: "鲫鱼住在清清的小河，那里不咸", py: "jì yú zhù zài qīng qīng de xiǎo hé，nà lǐ bù xián" },
      { t: "带鱼住在大大的海洋，那里咸咸的", py: "dài yú zhù zài dà dà de hǎi yáng，nà lǐ xián xián de" },
      { t: "把海水鱼放进淡水，它会生病", py: "bǎ hǎi shuǐ yú fàng jìn dàn shuǐ，tā huì shēng bìng" },
      { t: "把鲫鱼放进海水，它也活不久", py: "bǎ jì yú fàng jìn hǎi shuǐ，tā yě huó bù jiǔ" },
      { t: "咸淡不同，家的味道也不同", py: "xián dàn bù tóng，jiā de wèi dào yě bù tóng" },
      { t: "每一种鱼，都有自己最喜欢的家", py: "měi yī zhǒng yú，dōu yǒu zì jǐ zuì xǐ huan de jiā" },
      { t: "就像有人爱吃甜的，有人爱吃咸的一样自然", py: "jiù xiàng yǒu rén ài chī tián de，yǒu rén ài chī xián de yī yàng zì rán" },
      { t: "朋友再亲密，也要尊重彼此的生活环境", py: "péng you zài qīn mì，yě yào zūn zhòng bǐ cǐ de shēng huó huán jìng" },
    ],
    moral: "适合的才是最好的，不强求别人过自己的生活。",
    rhymelines: ["小鲫鱼爱淡水", "大带鱼爱海水", "咸淡各不同", "口安定海水"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "鲫鱼" },
      { char: "海", py: "hǎi", emoji: "🌊", word: "海洋" },
      { char: "河", py: "hé", emoji: "🏞️", word: "小河" },
      { char: "咸", py: "xián", emoji: "🧂", word: "咸咸的" },
    ],
    chars: ["河", "火", "马", "牛"],
    seq: {
      "河": "点 → 点 → 提 → 横 → 竖 → 横折 → 横 → 竖钩",
      "火": "点 → 撇 → 撇 → 捺",
      "马": "横折 → 竖折折钩 → 横",
      "牛": "撇 → 横 → 横 → 竖",
    },
    speak: ["鲫鱼爱吃淡水，带鱼爱住大海。", "咸淡不同的家，各有各的味道。", "适合的，才是最好的。"],
    quiz: [
      { p: "鲫鱼喜欢住哪里？", opt: [ {e:"🏞️",t:"不咸的小河",r:1}, {e:"🌊",t:"咸咸的大海"}, {e:"🗑️",t:"水沟"} ] },
      { p: "把海水鱼放淡水里会怎样？", opt: [ {e:"🤒",t:"生病",r:1}, {e:"🚀",t:"长得更快"}, {e:"🎉",t:"更开心"} ] },
      { p: "这个故事告诉我们？", opt: [ {e:"🏠",t:"适合的才是好的",r:1}, {e:"🌐",t:"什么都试一遍"}, {e:"🔄",t:"大家要一样"} ] },
    ],
    craft: '拿两杯水，一杯加盐一杯不加，让孩子分别"尝一尝"（只尝一点点）；再查一查：家里的鱼缸是淡水还是海水？（触觉味觉小实验）',
    parent: '用咸淡类比"每个人性格不同"：内向的孩子胆小，外向的孩子话多，都很好。让孩子尊重每一种"习惯"。',
  },

  13: {
    title: "大马哈鱼回家", sub: "逆流千里的决心", emoji: "🐟",
    story: [
      { t: "大马哈鱼在淡水里出生，在大海里长大", py: "dà mǎ hā yú zài dàn shuǐ lǐ chū shēng，zài dà hǎi lǐ zhǎng dà" },
      { t: "四年后的秋天，它要回到出生的河", py: "sì nián hòu de qiū tiān，tā yào huí dào chū shēng de hé" },
      { t: "它逆着水流，冲过瀑布和乱石", py: "tā nì zhe shuǐ liú，chōng guò pù bù hé luàn shí" },
      { t: "饿了瘦了，也不肯停下", py: "è le shòu le，yě bù kěn tíng xià" },
      { t: "千万条鱼，只有少数能游到老家", py: "qiān wàn tiáo yú，zhǐ yǒu shǎo shù néng yóu dào lǎo jiā" },
      { t: "它们拼尽全力，只为了家的召唤", py: "tā men pīn jìn quán lì，zhǐ wèi le jiā de zhào huàn" },
      { t: "它在水里闻到了家的味道，一刻也不敢歇", py: "tā zài shuǐ lǐ wén dào le jiā de wèi dào，yī kè yě bù gǎn xiē" },
      { t: "终于到达目的地，它用尽最后的力气产下鱼卵", py: "zhōng yú dào dá mù dì dì，tā yòng jìn zuì hòu de lì qi chǎn xià yú luǎn" },
      { t: "新生命会在这里出生，故事又会重新开始", py: "xīn shēng mìng huì zài zhè lǐ chū shēng，gù shì yòu huì chóng xīn kāi shǐ" },
    ],
    moral: "认准一个目标，哪怕一路逆流，也要坚持走到。",
    rhymelines: ["大海里长大", "秋天要回家", "逆着水流闯", "拼命不害怕"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "大马哈鱼" },
      { char: "河", py: "hé", emoji: "🏞️", word: "河流" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水流" },
      { char: "回", py: "huí", emoji: "↩️", word: "回家" },
    ],
    chars: ["回", "山", "田", "天"],
    seq: {
      "回": "竖 → 横折 → 横 → 横 → 竖 → 横折 → 横",
      "山": "竖 → 竖折 → 竖",
      "田": "竖 → 横折 → 横 → 竖 → 横",
      "天": "横 → 横 → 撇 → 捺",
    },
    speak: ["大马哈鱼逆着水流，冲过瀑布。", "认准目标，一路不回头。", "为了回家，再难也要坚持。"],
    quiz: [
      { p: "大马哈鱼在哪里长大？", opt: [ {e:"🌊",t:"大海",r:1}, {e:"🏠",t:"渔场"}, {e:"🏊",t:"泳池"} ] },
      { p: "秋天它要回到哪里？", opt: [ {e:"🏞️",t:"出生的河",r:1}, {e:"🌋",t:"火山口"}, {e:"🏜️",t:"沙漠"} ] },
      { p: "路上它要冲过什么？", opt: [ {e:"💦",t:"瀑布乱石",r:1}, {e:"🧱",t:"围墙"}, {e:"🚪",t:"大门"} ] },
    ],
    craft: '在地上铺一条"河流"（胶带弯弯曲曲），让孩子从"大海"爬到"老家"，爬过一个垫子当"瀑布"，感受逆流也要前进（大运动与毅力训练）。',
    parent: '孩子背单词、学拼音遇到"逆流"时，讲讲大马哈鱼。把目标拆小：这一周只坚持记住5个词，就是游过一段瀑布了。',
  },

  14: {
    title: "鳟鱼逆流而上", sub: "迎着困难向上游", emoji: "🏔️",
    story: [
      { t: "山溪里的鳟鱼，总爱迎着水流", py: "shān xī lǐ de zūn yú，zǒng ài yíng zhe shuǐ liú" },
      { t: "鱼群一起向上游，你推我挤不放弃", py: "yú qún yī qǐ xiàng shàng yóu，nǐ tuī wǒ jǐ bù fàng qì" },
      { t: "逆流让它们更强壮", py: "nì liú ràng tā men gèng qiáng zhuàng" },
      { t: "顺流很轻松，却会越漂越远", py: "shùn liú hěn qīng sōng，què huì yuè piāo yuè yuǎn" },
      { t: "小鳟鱼明白了：困难像水流，越是克服越有力", py: "xiǎo zūn yú míng bai le：kùn nán xiàng shuǐ liú，yuè shì kè fú yuè yǒu lì" },
      { t: "它们摆动尾巴，一下一下迎着浪花前进", py: "tā men bǎi dòng wěi ba，yī xià yī xià yíng zhe làng huā qián jìn" },
      { t: "累了就贴在石缝边喘口气，然后又出发", py: "lèi le jiù tiē zài shí fèng biān chuǎn kǒu qì，rán hòu yòu chū fā" },
      { t: "等游到山顶的清水潭，它们笑得像一道彩虹", py: "děng yóu dào shān dǐng de qīng shuǐ tán，tā men xiào dé xiàng yī dào cǎi hóng" },
    ],
    moral: "困难不是拦路虎，而是让脊背更硬的练功石。",
    rhymelines: ["小鳟鱼，挑战潮", "迎水流，变强壮", "困难多，本领高"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "鳟鱼" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水流" },
      { char: "上", py: "shàng", emoji: "⬆️", word: "上游" },
      { char: "山", py: "shān", emoji: "⛰️", word: "山溪" },
    ],
    chars: ["山", "水", "上", "下"],
    seq: {
      "山": "竖 → 竖折 → 竖",
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "上": "竖 → 横",
      "下": "横 → 竖 → 点",
    },
    speak: ["逆流让鳟鱼更强壮，也让小钓手更勇敢。", "困难像水流，克服了就有力量。", "迎难而上，越游越有力。"],
    quiz: [
      { p: "鳟鱼总爱迎着什么游？", opt: [ {e:"💨",t:"水流",r:1}, {e:"🌬️",t:"凉风"}, {e:"☀️",t:"阳光"} ] },
      { p: "逆流让鳟鱼怎么样？", opt: [ {e:"💪",t:"更强壮",r:1}, {e:"😵",t:"晕过去"}, {e:"🛌",t:"想睡觉"} ] },
      { p: "顺流很轻松，但会怎样？", opt: [ {e:"🌊",t:"越漂越远",r:1}, {e:"🏆",t:"更快长大"}, {e:"🎉",t:"更有力"} ] },
    ],
    craft: '玩一次"逆风前行"：开扇小风扇模拟水流，让孩子举着纸船迎风走向终点，感受"迎着困难走"（平衡与抗逆训练）。',
    parent: '作业变难时别急着帮孩子写完。先问："这段逆流你想怎么游？"让他自己制定两步走法，练习惯性勇敢。',
  },

  15: {
    title: "黑鱼护子", sub: "妈妈的爱最强大", emoji: "🖤",
    story: [
      { t: "黑鱼妈妈把宝宝们带在身边", py: "hēi yú mā ma bǎ bǎo bao men dài zài shēn biān" },
      { t: "谁要欺负小黑鱼，她就狠狠冲上去", py: "shuí yào qī fu xiǎo hēi yú，tā jiù hěn hěn chōng shàng qù" },
      { t: "小宝宝累了，黑鱼妈妈就背着游", py: "xiǎo bǎo bao lèi le，hēi yú mā ma jiù bēi zhe yóu" },
      { t: "猎人把她钓起来，她还是护着宝宝", py: "liè rén bǎ tā diào qǐ lái，tā hái shì hù zhe bǎo bao" },
      { t: "看，无论多危险，妈妈的爱从不缺席", py: "kàn，wú lùn duō wēi xiǎn，mā ma de ài cóng bù quē xí" },
      { t: "黑鱼妈妈守在孩子们周围，像一堵软软的墙", py: "hēi yú mā ma shǒu zài hái zi men zhōu wéi，xiàng yī dǔ ruǎn ruǎn de qiáng" },
      { t: "等宝宝们学会自己找吃的，她才悄悄松开手", py: "děng bǎo bao men xué huì zì jǐ zhǎo chī de，tā cái qiāo qiāo sōng kāi shǒu" },
      { t: "天下的妈妈都一样，把最爱藏进每个细节", py: "tiān xià de mā ma dōu yī yàng，bǎ zuì ài cáng jìn měi gè xì jié" },
    ],
    moral: '妈妈的爱很强大，也要记得对她说一声"谢谢"。',
    rhymelines: ["黑鱼妈妈护宝宝", "谁欺负她挡谁", "妈妈的爱好强大"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "黑鱼" },
      { char: "妈", py: "mā", emoji: "👩", word: "妈妈" },
      { char: "爱", py: "ài", emoji: "❤️", word: "关爱" },
      { char: "家", py: "jiā", emoji: "🏠", word: "我家" },
    ],
    chars: ["妈", "大", "小", "人"],
    seq: {
      "妈": "撇点 → 撇 → 横 → 竖折折钩 → 横",
      "大": "横 → 撇 → 捺",
      "小": "竖钩 → 撇 → 点",
      "人": "撇 → 捺",
    },
    speak: ["黑鱼妈妈护着宝宝，谁欺负就冲上去。", "妈妈的爱，从不缺席。", "谢谢妈妈，也把爱说出口。"],
    quiz: [
      { p: "黑鱼妈妈在干什么？", opt: [ {e:"🛡️",t:"护着宝宝",r:1}, {e:"😴",t:"睡大觉"}, {e:"🍴",t:"吃大餐"} ] },
      { p: "宝宝累了，黑鱼妈妈怎么办？", opt: [ {e:"🎒",t:"背着游",r:1}, {e:"🙅",t:"不管"}, {e:"📞",t:"打电话"} ] },
      { p: "这个故事让我们想到谁？", opt: [ {e:"👩",t:"妈妈",r:1}, {e:"🧑‍🏫",t:"数学老师"}, {e:"🚓",t:"警察"} ] },
    ],
    craft: '画一张"妈妈护着我"的画，把妈妈为你做过的事画成小鱼，贴起来；再对妈妈大声说一次"谢谢"（亲子情感表达）。',
    parent: '让爸爸也参与：讲完故事和孩子一起给妈妈准备小惊喜（倒杯水、捶捶肩），让孩子把"爱"说出口。',
  },

  16: {
    title: "鲫鱼和鲤鱼", sub: "鱼塘里的好邻居", emoji: "🐟",
    story: [
      { t: "鱼塘里住着一群鲫鱼和鲤鱼", py: "yú táng lǐ zhù zhe yī qún jì yú hé lǐ yú" },
      { t: "鲫鱼小巧，长得快，爱在浅水觅食", py: "jì yú xiǎo qiǎo，zhǎng dé kuài，ài zài qiǎn shuǐ mì shí" },
      { t: '鲤鱼嘴边有两条小胡子，是"挖土机"', py: "lǐ yú zuǐ biān yǒu liǎng tiáo xiǎo hú zi，shì wā tǔ jī" },
      { t: "它们一个吃水面虫，一个翻泥找食", py: "tā men yī gè chī shuǐ miàn chóng，yī gè fān ní zhǎo shí" },
      { t: "谁也不抢别人的饭，日子和和美美", py: "shuí yě bù qiǎng bié rén de fàn，rì zi hé hé měi měi" },
      { t: "天冷了，它们会凑在一起，人多更暖和", py: "tiān lěng le，tā men huì còu zài yī qǐ，rén duō gèng nuǎn huo" },
      { t: "鲫鱼在前面探路，鲤鱼在后面勤劳地翻土", py: "jì yú zài qián miàn tàn lù，lǐ yú zài hòu miàn qín láo de fān tǔ" },
      { t: "鱼塘里的小日子，就像一个大大的大家庭", py: "yú táng lǐ de xiǎo rì zi，jiù xiàng yī gè dà dà de dà jiā tíng" },
    ],
    moral: "各有各的本领，互相配合，日子就和和美美。",
    rhymelines: ["鲫鱼浅水找小虫", "鲤鱼泥里翻食找", "各有本领不吵闹"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "鲫鱼" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水面" },
      { char: "口", py: "kǒu", emoji: "👄", word: "嘴边" },
      { char: "泥", py: "ní", emoji: "🟫", word: "泥土" },
    ],
    chars: ["口", "田", "力", "火"],
    seq: {
      "口": "竖 → 横折 → 横",
      "田": "竖 → 横折 → 横 → 竖 → 横",
      "力": "横折钩 → 撇",
      "火": "点 → 撇 → 撇 → 捺",
    },
    speak: ["鲫鱼爱浅水，鲤鱼会挖泥。", "各有各的本领，谁也不抢饭。", "会合作的孩子，处处有朋友。"],
    quiz: [
      { p: "鲤鱼嘴边长了什么？", opt: [ {e:"🪒",t:"两条胡子",r:1}, {e:"🦷",t:"大牙"}, {e:"🎀",t:"蝴蝶结"} ] },
      { p: "鲫鱼爱在哪里吃东西？", opt: [ {e:"🏖️",t:"浅水",r:1}, {e:"🌋",t:"火山"}, {e:"🏔️",t:"山顶"} ] },
      { p: "它们俩会抢彼此的饭吗？", opt: [ {e:"🙅",t:"不会，各吃各的",r:1}, {e:"🥊",t:"会打架"}, {e:"🐛",t:"会偷吃"} ] },
    ],
    craft: '把孩子和兄弟姐妹/同学比作鲫鱼和鲤鱼：各用一张纸写下"我能做/你想做"，交换罗列，找出互补的"合作点"（人际智能）。',
    parent: '带孩子去菜市场认识真正的鲫鱼和鲤鱼，观察胡子；讲解"分工合作"，家庭家务也可两两搭配完成。',
  },

  17: {
    title: "鲈鱼公子", sub: "餐桌上的美味朋友", emoji: "🐠",
    story: [
      { t: "鲈鱼住在江水和海里，很会游", py: "lú yú zhù zài jiāng shuǐ hé hǎi lǐ，hěn huì yóu" },
      { t: "它背上有硬硬的鳍，像小帆", py: "tā bèi shàng yǒu yìng yìng de qí，xiàng xiǎo fān" },
      { t: "夜里鲈鱼游到岸边找小鱼吃", py: "yè lǐ lú yú yóu dào àn biān zhǎo xiǎo yú chī" },
      { t: "古人也爱吃鲈鱼，还写诗赞美它", py: "gǔ rén yě ài chī lú yú，hái xiě shī zàn měi tā" },
      { t: "秋风起了，就想着鲈鱼的美味", py: "qiū fēng qǐ le，jiù xiǎng zhe lú yú de měi wèi" },
      { t: '这是古人思乡的浪漫，叫作"莼鲈之思"', py: "zhè shì gǔ rén sī xiāng de làng màn，jiào zuò chún lú zhī sī" },
      { t: "从前的人读到诗，就像闻到了家乡饭的香味", py: "cóng qián de rén dú dào shī，jiù xiàng wén dào le jiā xiāng fàn de xiāng wèi" },
      { t: "等你也长大离开家，会明白这种想念有多美", py: "děng nǐ yě zhǎng dà lí kāi jiā，huì míng bai zhè zhǒng xiǎng niàn yǒu duō měi" },
    ],
    moral: "家乡的味道，会一直住在我们心里。记住了就格外珍惜。",
    rhymelines: ["鲈鱼背鳍像小帆", "古人写诗赞美它", "家乡味道最难忘"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "鲈鱼" },
      { char: "江", py: "jiāng", emoji: "🏞️", word: "江水" },
      { char: "风", py: "fēng", emoji: "🌬️", word: "秋风" },
      { char: "诗", py: "shī", emoji: "📜", word: "古诗" },
    ],
    chars: ["江", "风", "天", "田"],
    seq: {
      "江": "点 → 点 → 提 → 横 → 竖 → 横",
      "风": "撇 → 横折弯钩 → 撇 → 点",
      "天": "横 → 横 → 撇 → 捺",
      "田": "竖 → 横折 → 横 → 竖 → 横",
    },
    speak: ["鲈鱼背上的鳍，像一面小帆。", "秋风一起，古人就想起了鲈鱼。", "家乡的味道，永远最难忘。"],
    quiz: [
      { p: "鲈鱼住在哪里？", opt: [ {e:"🌊",t:"江水和海里",r:1}, {e:"🏜️",t:"沙漠"}, {e:"🏔️",t:"雪山"} ] },
      { p: "鲈鱼背上硬硬的鳍像什么？", opt: [ {e:"⛵",t:"小帆",r:1}, {e:"🍕",t:"披萨"}, {e:"🎏",t:"风筝"} ] },
      { p: '"莼鲈之思"表达了什么？', opt: [ {e:"🏠",t:"思念家乡",r:1}, {e:"🍽️",t:"只想吃鱼"}, {e:"😪",t:"无聊"} ] },
    ],
    craft: '一起查一查"他乡遇故知"的诗句，画画"我最想念的家乡味"，再用一句话介绍家乡的一道菜给全家听（语言表达与文化启蒙）。',
    parent: '家乡不一定是远方。聊聊自己小时候爱吃的家常菜，做一顿"记忆的味道"，把家族故事传下去。',
  },

  18: {
    title: "清道夫和草鱼", sub: "勤快的清洁工", emoji: "🌿",
    story: [
      { t: "鱼缸里的清道夫，天天贴着玻璃", py: "yú gāng lǐ de qīng dào fū，tiān tiān tiē zhe bō li" },
      { t: "它专吃青苔和水里的垃圾", py: "tā zhuān chī qīng tái hé shuǐ lǐ de lā jī" },
      { t: "池塘里的草鱼，专吃水草", py: "chí táng lǐ de cǎo yú，zhuān chī shuǐ cǎo" },
      { t: "水草太多会把鱼塘堵得慌慌的", py: "shuǐ cǎo tài duō huì bǎ yú táng dǔ dé huāng huāng de" },
      { t: "它们俩一内一外，把家打扫得干干净净", py: "tā men liǎ yī nèi yī wài，bǎ jiā dǎ sǎo dé gān gān jìng jìng" },
      { t: "清道夫吸呀吸，把玻璃擦得亮晶晶", py: "qīng dào fū xī ya xī，bǎ bō li cā dé liàng jīng jīng" },
      { t: "草鱼咔嚓咔嚓啃水草，池塘越吃越宽敞", py: "cǎo yú kā chā kā chā kěn shuǐ cǎo，chí táng yuè chī yuè kuān chǎng" },
      { t: "原来勤劳的小帮手，是大自然的功臣", py: "yuán lái qín láo de xiǎo bāng shǒu，shì dà zì rán de gōng chén" },
    ],
    moral: '认真做"小清洁工"，你也是班里的清道夫和草鱼。',
    rhymelines: ["清道夫，吸玻璃", "草鱼儿，吃水草", "家里家外都干净"],
    vocab: [
      { char: "草", py: "cǎo", emoji: "🌿", word: "水草" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "草鱼" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水滴" },
      { char: "天", py: "tiān", emoji: "☀️", word: "天天" },
    ],
    chars: ["草", "天", "木", "云"],
    seq: {
      "草": "横 → 竖 → 竖 → 竖 → 横折 → 横 → 横 → 横 → 竖",
      "天": "横 → 横 → 撇 → 捺",
      "木": "横 → 竖 → 撇 → 捺",
      "云": "横 → 横 → 撇折 → 点",
    },
    speak: ["清道夫专吃青苔和垃圾。", "草鱼专吃水草，水塘更通畅。", "勤快的小手，让家更干净。"],
    quiz: [
      { p: "清道夫喜欢吃什么都？", opt: [ {e:"🧹",t:"青苔垃圾",r:1}, {e:"🍔",t:"汉堡"}, {e:"🍎",t:"苹果"} ] },
      { p: "草鱼专门吃什么？", opt: [ {e:"🌿",t:"水草",r:1}, {e:"🪨",t:"石头"}, {e:"🍦",t:"冰激凌"} ] },
      { p: "水草太多了会怎样？", opt: [ {e:"😨",t:"堵住鱼塘",r:1}, {e:"🎉",t:"更热闹"}, {e:"🌈",t:"变彩色"} ] },
    ],
    craft: '做一张"清洁打卡表"：每天记录自己扫一次地、整理一次书桌，坚持五天得一颗小星星（习惯养成）。',
    parent: '把家务分工讲成"清道夫和草鱼"的小团队任务，孩子完成后给予具体表扬（"你把桌子擦得很干净"），强化责任感。',
  },

  19: {
    title: "钓鱼要看天气", sub: "看云识天气", emoji: "⛅",
    story: [
      { t: "爷爷说：钓鱼前先抬头看天", py: "yé ye shuō：diào yú qián xiān tái tóu kàn tiān" },
      { t: "白云朵朵，微风习习，最适合下竿", py: "bái yún duǒ duǒ，wēi fēng xí xí，zuì shì hé xià gān" },
      { t: "乌云压顶、雷声隆隆，赶紧收竿回家", py: "wū yún yā dǐng、léi shēng lóng lóng，gǎn jǐn shōu gān huí jiā" },
      { t: "刮大风时，鱼躲进水底不出来", py: "guā dà fēng shí，yú duǒ jìn shuǐ dǐ bù chū lái" },
      { t: "天好鱼欢喜，天坏鱼躲起", py: "tiān hǎo yú huān xǐ，tiān huài yú duǒ qǐ" },
      { t: "清晨的露水重，傍晚的霞光满天红", py: "qīng chén de lù shuǐ zhòng，bàng wǎn de xiá guāng mǎn tiān hóng" },
      { t: "爷爷还教他：蜻蜓低飞，雨将来临", py: "yé ye hái jiāo tā：qīng tíng dī fēi，yǔ jiāng lái lín" },
      { t: "出门前多看几眼天，钓鱼才更安全", py: "chū mén qián duō kàn jǐ yǎn tiān，diào yú cái gèng ān quán" },
      { t: "学会抬头看天，就学会和大自然做朋友", py: "xué huì tái tóu kàn tiān，jiù xué huì hé dà zì rán zuò péng you" },
    ],
    moral: '先观察再行动，少走好多弯路。做个看"脸色"的小聪明人。',
    rhymelines: ["白云朵朵好天气", "雷声隆隆快回家", "风大鱼躲水底游"],
    vocab: [
      { char: "天", py: "tiān", emoji: "☀️", word: "天气" },
      { char: "风", py: "fēng", emoji: "🌬️", word: "大风" },
      { char: "云", py: "yún", emoji: "☁️", word: "白云" },
      { char: "雨", py: "yǔ", emoji: "🌧️", word: "下雨" },
    ],
    chars: ["天", "云", "雨", "风"],
    seq: {
      "天": "横 → 横 → 撇 → 捺",
      "云": "横 → 横 → 撇折 → 点",
      "雨": "横 → 竖 → 横折钩 → 竖 → 点 → 点 → 点 → 点",
      "风": "撇 → 横折弯钩 → 撇 → 点",
    },
    speak: ["钓雨前先抬头看天。", "白云微风好下竿，打雷大风快回家。", "先观察再行动，少走弯路。"],
    quiz: [
      { p: "什么天气最适合钓鱼？", opt: [ {e:"☀️",t:"白云微风",r:1}, {e:"⛈️",t:"打雷下雨"}, {e:"🌪️",t:"龙卷风"} ] },
      { p: "看到乌云和雷声，应该？", opt: [ {e:"🏃",t:"赶紧回家",r:1}, {e:"🎣",t:"继续钓鱼"}, {e:"📸",t:"拍照发呆"} ] },
      { p: "刮大风时鱼会怎样？", opt: [ {e:"🫥",t:"躲进水底",r:1}, {e:"🎉",t:"跳上岸"}, {e:"🛻",t:"搬家"} ] },
    ],
    craft: '连续一周，每天用"云朵卡片"记录天空：晴☀️、阴☁️、雨🌧️，最后统计哪种天最多，试着把天气变成"数字"（气象观察表）。',
    parent: '和孩子一起下载天气APP看预报，第二天验证；把气象知识延展到"出门该带伞吗"，培养生活的预判力。',
  },

  20: {
    title: "水边的安全", sub: "安全永远第一", emoji: "⚠️",
    story: [
      { t: "小钓手们去河边，先听教练讲规则", py: "xiǎo diào shǒu men qù hé biān，xiān tīng jiào liàn jiǎng guī zé" },
      { t: "不许追跑打闹，岸边湿滑易摔", py: "bù xǔ zhuī pǎo dǎ nào，àn biān shī huá yì shuāi" },
      { t: "竿子甩开要把好方向，别钩到人", py: "gān zi shuǎi kāi yào bǎ hǎo fāng xiàng，bié gōu dào rén" },
      { t: "水再浅也不单独下水，呼叫大人来渡", py: "shuǐ zài qiǎn yě bù dān dú xià shuǐ，hū jiào dà rén lái dù" },
      { t: "安全排第一，快乐才久久", py: "ān quán pái dì yī，kuài lè cái jiǔ jiǔ" },
      { t: "救生衣要穿好，帽子要戴正，样样不能少", py: "jiù shēng yī yào chuān hǎo，mào zi yào dài zhèng，yàng yàng bù néng shǎo" },
      { t: "教练说：真正的勇敢，是先学会保护自己", py: "jiào liàn shuō：zhēn zhèng de yǒng gǎn，shì xiān xué huì bǎo hù zì jǐ" },
      { t: "把规则记在心里，快乐才会一直陪着你", py: "bǎ guī zé jì zài xīn lǐ，kuài lè cái huì yī zhí péi zhe nǐ" },
    ],
    moral: "会保护自己，才能钓到长长久久的快乐。",
    rhymelines: ["河边湿滑别乱跑", "甩竿看方向", "下水叫大人", "安全第一条"],
    vocab: [
      { char: "安", py: "ān", emoji: "🦺", word: "安全" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水面" },
      { char: "人", py: "rén", emoji: "🧍", word: "大人" },
      { char: "头", py: "tóu", emoji: "💯", word: "第一" },
    ],
    chars: ["安", "水", "大", "人"],
    seq: {
      "安": "点 → 点 → 横钩 → 撇 → 撇横撇 → 横",
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
      "人": "撇 → 捺",
    },
    speak: ["岸边湿滑，别追跑打闹。", "甩竿要看好身边有没有人。", "下水前，一定叫大人来。"],
    quiz: [
      { p: "在水边应该？", opt: [ {e:"🙅",t:"不追跑打闹",r:1}, {e:"🏃",t:"比赛跑步"}, {e:"🤸",t:"翻跟头"} ] },
      { p: "甩竿时要注意什么？", opt: [ {e:"👀",t:"别钩到人",r:1}, {e:"📷",t:"拍照"}, {e:"🎵",t:"听音乐"} ] },
      { p: "想下水应该怎么做？", opt: [ {e:"🧑",t:"叫大人来",r:1}, {e:"🦸",t:"自己悄悄下"}, {e:"😤",t:"憋一口气跳"} ] },
    ],
    craft: '和孩子画一张"水边安全牌"：上面画"可以/不可以"两个小人，贴到门口；下次出钓前先看一下（安全意识内化）。',
    parent: '安全守则要"演练"而不是"讲一遍"。带孩子在家模拟：哪种情况打电话求助？走丢了怎么办？反复排练防患于未然。',
  },

  21: {
    title: "放流，钓鱼人的品格", sub: "钓大放小、爱护家园", emoji: "🤝",
    story: [
      { t: "小鱼儿还不到一指长，太娇小", py: "xiǎo yú ér hái bù dào yī zhǐ cháng，tài jiāo xiǎo" },
      { t: "老钓手把它轻轻放回水里", py: "lǎo diào shǒu bǎ tā qīng qīng fàng huí shuǐ lǐ" },
      { t: "有的钓手钓到大鱼也会放流", py: "yǒu de diào shǒu diào dào dà yú yě huì fàng liú" },
      { t: "说：让有鱼仔的鱼妈妈继续长大", py: "shuō：ràng yǒu yú zǎi de yú mā ma jì xù zhǎng dà" },
      { t: "今天放流的鱼，是明天更多的鱼", py: "jīn tiān fàng liú de yú，shì míng tiān gèng duō de yú" },
      { t: "小鱼摆摆尾巴，好像在对钓手说谢谢你", py: "xiǎo yú bǎi bǎi wěi ba，hǎo xiàng zài duì diào shǒu shuō xiè xie nǐ" },
      { t: "钓鱼的快乐，不止是带走，也包括放手", py: "diào yú de kuài lè，bù zhǐ shì dài zǒu，yě bāo kuò fàng shǒu" },
      { t: "爱护鱼儿，就是爱护我们共同的家园", py: "ài hù yú ér，jiù shì ài hù wǒ men gòng tóng de jiā yuán" },
    ],
    moral: '爱护家园，就是爱护明天的自己。做个懂得"放"的钓手。',
    rhymelines: ["小鱼儿，放回去", "大鱼仔，也放游", "明天鱼儿更多了"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "小鱼" },
      { char: "放", py: "fàng", emoji: "🕊️", word: "放流" },
      { char: "家", py: "jiā", emoji: "🏠", word: "家园" },
      { char: "天", py: "tiān", emoji: "☀️", word: "明天" },
    ],
    chars: ["放", "大", "山", "云"],
    seq: {
      "放": "点 → 横 → 横折钩 → 撇 → 撇 → 横 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
      "山": "竖 → 竖折 → 竖",
      "云": "横 → 横 → 撇折 → 点",
    },
    speak: ["小鱼太娇小，轻轻放回水里。", "今天放流的鱼，是明天的更多鱼。", "爱家园，就是爱明天的自己。"],
    quiz: [
      { p: "一指长的小鱼应该？", opt: [ {e:"🔄",t:"放回水里",r:1}, {e:"🍳",t:"煮着吃"}, {e:"🎁",t:"送人"} ] },
      { p: "钓手放流大鱼，是为了？", opt: [ {e:"🐠",t:"让鱼妈妈继续养仔",r:1}, {e:"😅",t:"嫌它太难吃"}, {e:"📸",t:"腾出鱼桶"} ] },
      { p: "爱护家园就是爱护什么？", opt: [ {e:"⭐",t:"明天的自己",r:1}, {e:"🌕",t:"月亮"}, {e:"👻",t:"外星人"} ] },
    ],
    craft: '做一个"放流承诺卡"：写上"我承诺钓大放小"，画一条小鱼和一个大大的笑脸，签上名字贴书桌（承诺意识）。',
    parent: '这不是只关于钓鱼：把"放流"延伸到不乱丢垃圾、不浪费水电，让孩子明白"留一线"是对未来的善意。',
  },

  22: {
    title: "钓场公约", sub: "做个讲礼貌的小钓手", emoji: "📜",
    story: [
      { t: "钓场门口挂着一块公约牌子", py: "diào chǎng mén kǒu guà zhe yī kuài gōng yuē pái zi" },
      { t: "第一条：轻声说话，不吓走鱼", py: "dì yī tiáo：qīng shēng shuō huà，bù xià zǒu yú" },
      { t: "第二条：鱼线离人远一点", py: "dì èr tiáo：yú xiàn lí rén yuǎn yī diǎn" },
      { t: "第三条：自己的垃圾自己带走", py: "dì sān tiáo：zì jǐ de lā jī zì jǐ dài zǒu" },
      { t: "小钓手一项项记下来，笑呵呵地做", py: "xiǎo diào shǒu yī xiàng xiàng jì xià lái，xiào hē hē de zuò" },
      { t: "人人守公约，钓场就总是热闹又干净", py: "rén rén shǒu gōng yuē，diào chǎng jiù zǒng shì rè nào yòu gān jìng" },
      { t: "他还提醒身边的小朋友：帮别人捡起一片纸屑", py: "tā hái tí xǐng shēn biān de xiǎo péng you：bāng bié rén jiǎn qǐ yī piàn zhǐ xiè" },
      { t: "笑着分享自己带来的小饼干，钓场更温馨", py: "xiào zhe fēn xiǎng zì jǐ dài lái de xiǎo bǐng gān，diào chǎng gèng wēn xīn" },
    ],
    moral: "守规矩不是束缚，是大家一起把快乐留久一点。",
    rhymelines: ["轻声说话不吓鱼", "鱼线离人远一点", "垃圾自己带回家"],
    vocab: [
      { char: "人", py: "rén", emoji: "🧍", word: "人人" },
      { char: "公", py: "gōng", emoji: "📜", word: "公约" },
      { char: "手", py: "shǒu", emoji: "✋", word: "小手" },
      { char: "自", py: "zì", emoji: "🙋", word: "自己" },
    ],
    chars: ["人", "公", "手", "自"],
    seq: {
      "人": "撇 → 捺",
      "公": "撇 → 捺 → 撇折 → 点",
      "手": "撇 → 横 → 横 → 竖钩",
      "自": "撇 → 竖 → 横折 → 横 → 横 → 横",
    },
    speak: ["轻声说话，鱼儿不惊。", "自己的垃圾，自己带走。", "守公约，快乐留更久。"],
    quiz: [
      { p: "在钓场应该怎么说话？", opt: [ {e:"🤫",t:"轻声细语",r:1}, {e:"📣",t:"大声喊叫"}, {e:"🎷",t:"吹喇叭"} ] },
      { p: "自己的垃圾应该？", opt: [ {e:"🎒",t:"自己带走",r:1}, {e:"🌊",t:"丢进水里"}, {e:"🗑️",t:"顺手乱放"} ] },
      { p: "人人守规约，钓场会怎样？", opt: [ {e:"✨",t:"热闹又干净",r:1}, {e:"😟",t:"乱糟糟"}, {e:"🚫",t:"关门"} ] },
    ],
    craft: '为家里的书桌定3条"书桌公约"，画成小海报贴墙上；每天对照检查自己的遵守项，得满就有小红花（规则意识）。',
    parent: '让孩子在聚餐、出游前"宣布"自己的公约三条，练表达的同时把公德心种在心里。',
  },

  23: {
    title: "鱼会睡觉吗", sub: "睁着眼睛的睡眠", emoji: "🌙",
    story: [
      { t: "小钓手夜里睡不着：鱼会睡觉吗？", py: "xiǎo diào shǒu yè lǐ shuì bù zháo：yú huì shuì jiào ma？" },
      { t: "爸爸说：会呀，鱼也要休息", py: "bà ba shuō：huì ya，yú yě yào xiū xi" },
      { t: "可是鱼没有眼皮，眼睛闭不上", py: "kě shì yú méi yǒu yǎn pí，yǎn jīng bì bù shàng" },
      { t: "它们就静静地浮着，或者躲进水里", py: "tā men jiù jìng jìng de fú zhe，huò zhě duǒ jìn shuǐ lǐ" },
      { t: "有些鱼睡觉还睁着眼睛，像盯着你看", py: "yǒu xiē yú shuì jiào hái zhēng zhe yǎn jīng，xiàng dīng zhe nǐ kàn" },
      { t: "知道这个小秘密，小钓手安心睡着了", py: "zhī dào zhè gè xiǎo mì mì，xiǎo diào shǒu ān xīn shuì zháo le" },
      { t: "其实它们的大脑，也会慢下来好好休息", py: "qí shí tā men de dà nǎo，yě huì màn xià lái hǎo hǎo xiū xi" },
      { t: "第二天他得意地讲给朋友，把大家都逗笑了", py: "dì èr tiān tā dé yì de jiǎng gěi péng you，bǎ dà jiā dōu dòu xiào le" },
    ],
    moral: "世界这么大，问题问不完，答案要自己去探索。",
    rhymelines: ["小鱼儿，睡觉觉", "没有眼皮闭不上", "睁大眼睛也在睡"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "小鱼" },
      { char: "眼", py: "yǎn", emoji: "👀", word: "眼睛" },
      { char: "睡", py: "shuì", emoji: "🌙", word: "睡觉" },
      { char: "夜", py: "yè", emoji: "🌃", word: "夜晚" },
    ],
    chars: ["上", "山", "口", "小"],
    seq: {
      "上": "竖 → 横",
      "山": "竖 → 竖折 → 竖",
      "口": "竖 → 横折 → 横",
      "小": "竖钩 → 撇 → 点",
    },
    speak: ["鱼没有眼皮，睁着眼睛睡觉。", "静静浮着，就是在休息。", "世界很大，答案靠自己去发现。"],
    quiz: [
      { p: "鱼睡觉时眼睛怎么样？", opt: [ {e:"👀",t:"闭不上",r:1}, {e:"😴",t:"闭得紧紧的"}, {e:"🕶️",t:"戴眼罩"} ] },
      { p: "鱼休息时会怎样？", opt: [ {e:"🧘",t:"静静浮着",r:1}, {e:"🏃",t:"来回冲刺"}, {e:"🎤",t:"唱歌"} ] },
      { p: "这个故事鼓励我们？", opt: [ {e:"🔍",t:"多问多探索",r:1}, {e:"🛌",t:"一直睡懒觉"}, {e:"🙈",t:"假装没看见"} ] },
    ],
    craft: '晚上关灯后用手电筒照鱼缸，观察金鱼是否安静"睡觉"；再在自己眼皮上贴纯水湿巾模拟"睁眼睡"（安全有趣的观察实验）。',
    parent: '把"为什么"当作宝贵的礼物，鼓励孩子提问并一起查书/查资料，培养"终生学习者"心智。',
  },

  24: {
    title: "鱼为什么跃出水面", sub: "好奇的泡泡问题", emoji: "💦",
    story: [
      { t: "湖面上突然跳出一条鱼，又扎回水里", py: "hú miàn shàng tū rán tiào chū yī tiáo yú，yòu zhā huí shuǐ lǐ" },
      { t: "小钓手问：鱼儿也想看看天空吗？", py: "xiǎo diào shǒu wèn：yú ér yě xiǎng kàn kàn tiān kōng ma？" },
      { t: "教练说：有时候是躲避大鱼，有时候是玩", py: "jiào liàn shuō：yǒu shí hou shì duǒ bì dà yú，yǒu shí hou shì wán" },
      { t: "夏天的傍晚，飞虫多，鱼也跳起来吃", py: "xià tiān de bàng wǎn，fēi chóng duō，yú yě tiào qǐ lái chī" },
      { t: '鱼跃出水面，是在和我们说"哈哈我在这儿"', py: "yú yuè chū shuǐ miàn，shì zài hé wǒ men shuō hā hā wǒ zài zhè ér" },
      { t: "跳起来的时候，它的鳞片在阳光下闪闪发光", py: "tiào qǐ lái de shí hou，tā de lín piàn zài yáng guāng xià shǎn shǎn fā guāng" },
      { t: "小钓手记住了：鱼儿也有自己的语言和表达", py: "xiǎo diào shǒu jì zhù le：yú ér yě yǒu zì jǐ de yǔ yán hé biǎo dá" },
    ],
    moral: "好奇没问题，问出好问题，世界就多打开一扇窗。",
    rhymelines: ["小鱼跳出水面来", "躲大鱼，吃飞虫", "问问它是为了啥"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "小鱼" },
      { char: "水", py: "shuǐ", emoji: "💧", word: "水面" },
      { char: "跳", py: "tiào", emoji: "🦘", word: "跳起来" },
      { char: "玩", py: "wán", emoji: "🎮", word: "玩耍" },
    ],
    chars: ["水", "大", "天", "云"],
    seq: {
      "水": "竖钩 → 横撇 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
      "天": "横 → 横 → 撇 → 捺",
      "云": "横 → 横 → 撇折 → 点",
    },
    speak: ["鱼跳出水面，可能是在玩。", "也可能是躲大鱼、吃飞虫。", "多问为什么，世界多开一扇窗。"],
    quiz: [
      { p: "鱼跃出水面，有时是为了？", opt: [ {e:"🦈",t:"躲大鱼",r:1}, {e:"🖼️",t:"看画展"}, {e:"💅",t:"做面膜"} ] },
      { p: "夏天的傍晚，鱼跳起来吃什么？", opt: [ {e:"🪰",t:"飞虫",r:1}, {e:"🍟",t:"薯条"}, {e:"🍗",t:"鸡腿"} ] },
      { p: "教练说鱼跃出水有时也是为了？", opt: [ {e:"🪀",t:"玩耍",r:1}, {e:"😰",t:"考试"}, {e:"🗣️",t:"吵架"} ] },
    ],
    craft: '在浴缸或大盆里放一个漂浮的球，往外弹/拨水，观察"水的反应"；再玩"青蛙跳"，模拟鱼跃出水的曲线（动作与观察结合）。',
    parent: '把孩子的"为什么"记在本子上攒起来，每周一起研究一个，做成迷你科普海报，呵护好奇心。',
  },

  25: {
    title: "钓行日记", sub: "记录我的每一次出钓", emoji: "📔",
    story: [
      { t: "教练给小钓手们发了一本钓行日记", py: "jiào liàn gěi xiǎo diào shǒu men fā le yī běn diào xíng rì jì" },
      { t: "写上日期、天气、钓点", py: "xiě shàng rì qī、tiān qì、diào diǎn" },
      { t: "画下今天钓到的鱼，大大的鱼最开心", py: "huà xià jīn tiān diào dào de yú，dà dà de yú zuì kāi xīn" },
      { t: "还要记一下：今天学了什么新动作", py: "hái yào jì yī xià：jīn tiān xué le shén me xīn dòng zuò" },
      { t: "一点点记下来，回头一看，哇，进步好大", py: "yī diǎn diǎn jì xià lái，huí tóu yī kàn，wā，jìn bù hǎo dà" },
      { t: "他还给每一条钓到的鱼起了可爱的名字", py: "tā hái gěi měi yī tiáo diào dào de yú qǐ le kě ài de míng zi" },
      { t: "日记越写越厚，他的本领也越来越高", py: "rì jì yuè xiě yuè hòu，tā de běn lǐng yě yuè lái yuè gāo" },
      { t: "等到冬天翻开日记，就像重游了一遍夏天", py: "děng dào dōng tiān fān kāi rì jì，jiù xiàng zhòng yóu le yī biàn xià tiān" },
    ],
    moral: "把每天的小记录攒起来，就是看得见的成长。",
    rhymelines: ["小日记，记钓行", "日期天气画上鱼", "回看都是大进步"],
    vocab: [
      { char: "记", py: "jì", emoji: "📝", word: "日记" },
      { char: "天", py: "tiān", emoji: "☀️", word: "每天" },
      { char: "字", py: "zì", emoji: "🎓", word: "写字" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "钓鱼" },
    ],
    chars: ["记", "字", "天", "大"],
    seq: {
      "记": "点 → 横折提 → 横折 → 横 → 竖弯钩",
      "字": "点 → 点 → 横钩 → 横撇 → 横钩 → 竖钩 → 横",
      "天": "横 → 横 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
    },
    speak: ["钓完鱼，记一记今天的天气和心得。", "小记录攒起来，就是看得见的进步。", "写日记的孩子，心里有条小河。"],
    quiz: [
      { p: "钓行日记里要写什么？", opt: [ {e:"📅",t:"日期天气",r:1}, {e:"🌈",t:"彩虹颜色"}, {e:"💰",t:"糖果价格"} ] },
      { p: "画下今天的鱼，哪种最开心？", opt: [ {e:"🐋",t:"超大的鱼",r:1}, {e:"🐞",t:"小瓢虫"}, {e:"🐌",t:"小蜗牛"} ] },
      { p: "回看日记能发现什么？", opt: [ {e:"🚀",t:"自己进步好大",r:1}, {e:"😴",t:"什么也没变"}, {e:"🌧️",t:"天天下雨"} ] },
    ],
    craft: '做一个"打卡日历"：每天写一个当天学会的词或画一样东西，30天后连起来看，就是一条成长的"鱼线"（持续记录习惯）。',
    parent: '给孩子备一个专属小本子，每晚一起记录"今天我做到的一件好事"，坚持一个月后再回看，让孩子看见坚持的力量。',
  },

  26: {
    title: "秤鱼与量尺", sub: "钓鱼人的尺子", emoji: "📏",
    story: [
      { t: "钓到一条鱼，先量一量有多长", py: "diào dào yī tiáo yú，xiān liáng yī liáng yǒu duō cháng" },
      { t: "再用秤称一称有多重", py: "zài yòng chèng chēng yī chēng yǒu duō zhòng" },
      { t: "把数字记在日记里，下次比较", py: "bǎ shù zì jì zài rì jì lǐ，xià cì bǐ jiào" },
      { t: "数学悄悄溜进了钓鱼里", py: "shù xué qiāo qiāo liū jìn le diào yú lǐ" },
      { t: "小钓手发现：厘米、克，都成了好朋友", py: "xiǎo diào shǒu fā xiàn：lí mǐ、kè，dōu chéng le hǎo péng you" },
      { t: "他还会比一比：上周的大还是这周的大", py: "tā hái huì bǐ yī bǐ：shàng zhōu de dà hái shì zhè zhōu de dà" },
      { t: "他把量好的长度认真记在小本子上", py: "tā bǎ liáng hǎo de cháng dù rèn zhēn jì zài xiǎo běn zi shàng" },
      { t: "爸爸笑着夸他：真像个小科学家", py: "bà ba xiào zhe kuā tā：zhēn xiàng gè xiǎo kē xué jiā" },
      { t: "原来学习就藏在每一个好玩的游戏里", py: "yuán lái xué xí jiù cáng zài měi yī gè hǎo wán de yóu xì lǐ" },
    ],
    moral: "学习无处不在，动手测量，数字就活在手上。",
    rhymelines: ["钓到鱼，先量量", "长多少，重多少", "数字朋友悄悄来"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "钓鱼" },
      { char: "大", py: "dà", emoji: "🐻", word: "大小" },
      { char: "长", py: "cháng", emoji: "📏", word: "长度" },
      { char: "手", py: "shǒu", emoji: "🗒️", word: "用手量" },
    ],
    chars: ["手", "尺", "大", "小"],
    seq: {
      "手": "撇 → 横 → 横 → 竖钩",
      "尺": "横折 → 横 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
      "小": "竖钩 → 撇 → 点",
    },
    speak: ["钓到鱼先量长度、称重量。", "数字记下来，下次更进步。", "动手测量，数学就在手上。"],
    quiz: [
      { p: "钓到鱼第一件事做什么？", opt: [ {e:"📏",t:"量一量",r:1}, {e:"🧂",t:"撒调料"}, {e:"📸",t:"先发朋友圈"} ] },
      { p: "用尺子量的是什么？", opt: [ {e:"↔️",t:"长度",r:1}, {e:"🎨",t:"颜色"}, {e:"🎵",t:"声音"} ] },
      { p: "这些数字可以用来做什么？", opt: [ {e:"📊",t:"记录比较",r:1}, {e:"🪄",t:"变魔术"}, {e:"🌀",t:"转圈圈"} ] },
    ],
    craft: '用量衣尺/软尺量家里5样东西（桌子、水杯、床、门、爸爸的手），把结果写下来排序，做成"家里的小测量员"表格（数学应用）。',
    parent: '和孩子一起看秤（鱼尺/体重秤）读数，认识g/kg/cm/m。让阿姨做饭时"称一称"分量，把单位用活。',
  },

  27: {
    title: "鱼线的秘密", sub: "细丝里的大学问", emoji: "🎗️",
    story: [
      { t: "这根细细的钓线，能吊起几斤重的大鱼", py: "zhè gēn xì xì de diào xiàn，néng diào qǐ jǐ jīn zhòng de dà yú" },
      { t: "有的线弹性好，能缓冲鱼的挣扎", py: "yǒu de xiàn tán xìng hǎo，néng huǎn chōng yú de zhēng zhá" },
      { t: "有的线透明，鱼不容易发现", py: "yǒu de xiàn tòu míng，yú bù róng yì fā xiàn" },
      { t: '越细越轻，却越要"耐用"', py: "yuè xì yuè qīng，què yuè yào nài yòng" },
      { t: "长长的鱼线，缠的是材料科学的秘密", py: "cháng cháng de yú xiàn，chán de shì cái liào kē xué de mì mì" },
      { t: "科学家用小小的鱼线，造出了结实的桥索", py: "kē xué jiā yòng xiǎo xiǎo de yú xiàn，zào chū le jié shi de qiáo suǒ" },
      { t: "小钓手摸摸鱼线，对科学多了一份敬佩", py: "xiǎo diào shǒu mō mō yú xiàn，duì kē xué duō le yī fèn jìng pèi" },
      { t: "原来一根细线，也能撑起大大的梦想", py: "yuán lái yī gēn xì xiàn，yě néng chēng qǐ dà dà de mèng xiǎng" },
    ],
    moral: '越小的东西越有大学问，别小看身边任何一件"小事"。',
    rhymelines: ["细细鱼线大学问", "弹性好又透明", "材料科学藏里头"],
    vocab: [
      { char: "线", py: "xiàn", emoji: "🎗️", word: "鱼线" },
      { char: "大", py: "dà", emoji: "🐻", word: "大鱼" },
      { char: "细", py: "xì", emoji: "🧵", word: "细线" },
      { char: "长", py: "cháng", emoji: "📏", word: "长长" },
    ],
    chars: ["线", "长", "小", "大"],
    seq: {
      "线": "撇折 → 撇折 → 提 → 横 → 横 → 斜钩 → 撇 → 点",
      "长": "撇 → 横 → 竖提 → 捺",
      "小": "竖钩 → 撇 → 点",
      "大": "横 → 撇 → 捺",
    },
    speak: ["细鱼线能吊起大鱼，因为材料有学问。", "有的线透明，鱼发现不了。", "别小看身边一件小事，里面都有大学问。"],
    quiz: [
      { p: "有的钓线为什么要透明？", opt: [ {e:"🎭",t:"让鱼发现不了",r:1}, {e:"💅",t:"更好看"}, {e:"🌞",t:"防晒"} ] },
      { p: "弹性好的线有什么好处？", opt: [ {e:"🥊",t:"缓冲鱼的挣扎",r:1}, {e:"🍬",t:"更甜"}, {e:"📻",t:"收音更好"} ] },
      { p: "这个故事告诉我们？", opt: [ {e:"🔬",t:"小事里也有大科学",r:1}, {e:"🧹",t:"东西越重越好"}, {e:"🛑",t:"线越粗越好"} ] },
    ],
    craft: '试试用一根棉线、一根玻璃线（耐高温透明线）、一段毛线，分别拴上重物，感受谁的"强度"和"拉力"更好（材料小实验）。',
    parent: '从鱼线聊到"为什么桥上的钢索细细的却能吊住大桥"，带出"材料科学"启蒙，同样适用于网线、牙线。',
  },

  28: {
    title: "渔家谚语", sub: "老祖宗的钓鱼智慧", emoji: "🀄",
    story: [
      { t: "爷爷总爱念叨渔家谚语", py: "yé ye zǒng ài niàn dāo yú jiā yàn yǔ" },
      { t: '"春钓滩，夏钓潭，秋钓阴，冬钓阳"', py: "chūn diào tān，xià diào tán，qiū diào yīn，dōng diào yáng" },
      { t: "春天鱼爱到浅滩晒太阳", py: "chūn tiān yú ài dào qiǎn tān shài tài yang" },
      { t: "夏天天热，鱼躲到深水潭底", py: "xià tiān tiān rè，yú duǒ dào shēn shuǐ tán dǐ" },
      { t: "跟着节气走，钓鱼不用愁", py: "gēn zhe jié qì zǒu，diào yú bù yòng chóu" },
      { t: "每种鱼在四季有不同的脾气，看懂了就钓得到", py: "měi zhǒng yú zài sì jì yǒu bù tóng de pí qi，kàn dǒng le jiù diào dé dào" },
      { t: "智慧不在书本里，就在渔夫的笑容里", py: "zhì huì bù zài shū běn lǐ，jiù zài yú fū de xiào róng lǐ" },
      { t: "小钓手把谚语背得滚瓜烂熟，逢人就说给人家听", py: "xiǎo diào shǒu bǎ yàn yǔ bèi dé gǔn guā làn shú，féng rén jiù shuō gěi rén jia tīng" },
    ],
    moral: "老祖宗把智慧藏在短句里，学会听、学着用。",
    rhymelines: ["春钓滩，夏钓潭", "秋钓阴，冬钓阳", "跟着节气钓鱼忙"],
    vocab: [
      { char: "鱼", py: "yú", emoji: "🐟", word: "钓鱼" },
      { char: "春", py: "chūn", emoji: "🌷", word: "春天" },
      { char: "夏", py: "xià", emoji: "☀️", word: "夏天" },
      { char: "冬", py: "dōng", emoji: "❄️", word: "冬天" },
    ],
    chars: ["春", "天", "大", "万"],
    seq: {
      "春": "横 → 横 → 横 → 撇 → 捺 → 竖 → 横折 → 横 → 横",
      "天": "横 → 横 → 撇 → 捺",
      "大": "横 → 撇 → 捺",
      "万": "横 → 横折钩 → 撇",
    },
    speak: ["春钓滩，夏钓潭，秋钓阴，冬钓阳。", "跟着节气走，钓鱼不用愁。", "老祖宗的短句，藏着大智慧。"],
    quiz: [
      { p: "春天应该在哪里钓？", opt: [ {e:"🏖️",t:"浅滩",r:1}, {e:"🏔️",t:"山顶湖"}, {e:"🏊",t:"深水泳池"} ] },
      { p: "夏天鱼躲到哪里？", opt: [ {e:"🫧",t:"深水潭",r:1}, {e:"🌵",t:"沙滩伞下"}, {e:"🏠",t:"洞穴里"} ] },
      { p: "这条谚语告诉我们要？", opt: [ {e:"🗓️",t:"跟着节气走",r:1}, {e:"🎲",t:"碰运气"}, {e:"🚀",t:"乱跑乱试"} ] },
    ],
    craft: '做一年四季的"钓鱼地点小转盘"：四季四格（滩/潭/阴/阳），每格画一画，转动后再猜谚语（节气文化游戏）。',
    parent: '带孩子背诵这首"钓鱼节气歌"，并一起观察四季的自然变化，把谚语当成观察手册，联系生活经验。',
  },

  29: {
    title: "我的钓鱼故事", sub: "把30天讲给家人听", emoji: "🗣️",
    story: [
      { t: "小钓手们围成一圈，分享自己的钓鱼故事", py: "xiǎo diào shǒu men wéi chéng yī quān，fēn xiǎng zì jǐ de diào yú gù shì" },
      { t: "有的讲第一次钓到鱼的心跳", py: "yǒu de jiǎng dì yī cì diào dào yú de xīn tiào" },
      { t: '有的讲鱼挣脱鱼钩的"大冒险"', py: "yǒu de jiǎng yú zhèng tuō yú gōu de dà mào xiǎn" },
      { t: "把有的讲放流小鱼时的不舍", py: "bǎ yǒu de jiǎng fàng liú xiǎo yú shí de bù shě" },
      { t: "讲着讲着，大家都笑了，心里暖暖的", py: "jiǎng zhe jiǎng zhe，dà jiā dōu xiào le，xīn lǐ nuǎn nuǎn de" },
      { t: "记录和表达，是钓手最亮的鱼竿", py: "jì lù hé biǎo dá，shì diào shǒu zuì liàng de yú gān" },
      { t: "最好笑的是小鱼太轻，被风一吹就飘走了", py: "zuì hǎo xiào de shì xiǎo yú tài qīng，bèi fēng yī chuī jiù piāo zǒu le" },
      { t: "教练说：每个故事里，都住着你们长大的样子", py: "jiào liàn shuō：měi gè gù shì lǐ，dōu zhù zhe nǐ men zhǎng dà de yàng zi" },
    ],
    moral: "会讲故事的人，心里住着一整个湖。把你眼睛看到的，都说出来。",
    rhymelines: ["围成圈，讲故事", "鱼儿心里暖暖的", "故事是闪亮鱼竿"],
    vocab: [
      { char: "讲", py: "jiǎng", emoji: "🎤", word: "讲故事" },
      { char: "我", py: "wǒ", emoji: "🙋", word: "我的" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "钓鱼" },
      { char: "口", py: "kǒu", emoji: "🗣️", word: "开心" },
    ],
    chars: ["我", "口", "大", "木"],
    seq: {
      "我": "撇 → 横 → 竖钩 → 提 → 斜钩 → 撇 → 点",
      "口": "竖 → 横折 → 横",
      "大": "横 → 撇 → 捺",
      "木": "横 → 竖 → 撇 → 捺",
    },
    speak: ["讲出你的钓鱼故事，就是闪亮的鱼竿。", "把看见的、感受到的，都说出来。", "会表达的孩子，心里住着一片湖。"],
    quiz: [
      { p: "小钓手们围着做什么？", opt: [ {e:"💬",t:"分享故事",r:1}, {e:"🍕",t:"吃比萨"}, {e:"🎮",t:"打游戏"} ] },
      { p: "讲完故事，大家心里怎样？", opt: [ {e:"🥰",t:"暖暖的",r:1}, {e:"😴",t:"困了"}, {e:"😣",t:"很烦"} ] },
      { p: "记录和表达是什么？", opt: [ {e:"🎣",t:"钓手最亮的鱼竿",r:1}, {e:"🪵",t:"普通的棍子"}, {e:"🚩",t:"红领巾"} ] },
    ],
    craft: '开一场"家庭脱口秀"：孩子做主持人，采访爷爷/爸爸"你小时候最难忘的一件事"，全家轮流讲故事（听说与采访训练）。',
    parent: "鼓励孩子把今天钓的鱼、学的字讲给全家；认真倾听并追问细节，这会让孩子爱上表达。",
  },

  30: {
    title: "光荣毕业", sub: "钓手证书颁发仪式", emoji: "🎓",
    story: [
      { t: "三十天，我们从直钩钓到大鱼", py: "sān shí tiān，wǒ men cóng zhí gōu diào dào dà yú" },
      { t: "学会了耐心、坚持、感恩和安全", py: "xué huì le nài xīn、jiān chí、gǎn ēn hé ān quán" },
      { t: '教练端出大大的"钓手证书"', py: "jiào liàn duān chū dà dà de diào shǒu zhèng shū" },
      { t: "每个孩子领到证书，站得笔直", py: "měi gè hái zi lǐng dào zhèng shū，zhàn dé bǐ zhí" },
      { t: "教练说：毕业不是终点，是正式出钓的开始", py: "jiào liàn shuō：bì yè bù shì zhōng diǎn，shì zhèng shì chū diào de kāi shǐ" },
      { t: "小溪叮当响，钓手的路还很长嘞", py: "xiǎo xī dīng dāng xiǎng，diào shǒu de lù hái hěn cháng lei" },
      { t: "大家把证书举高高，对着天空比了一个大大的耶", py: "dà jiā bǎ zhèng shū jǔ gāo gāo，duì zhe tiān kōng bǐ le yī gè dà dà de yē" },
      { t: "钓手叔叔挥手道别：记得常回来看我们呀", py: "diào shǒu shū shu huī shǒu dào bié：jì dé cháng huí lái kàn wǒ men ya" },
    ],
    moral: "结束是另一种开始。带着学到的本领，去更大的湖边吧。",
    rhymelines: ["三十天，钓成手", "证书大，站得直", "毕业是新的开始"],
    vocab: [
      { char: "大", py: "dà", emoji: "🐻", word: "大事" },
      { char: "小", py: "xiǎo", emoji: "🐜", word: "小小的" },
      { char: "鱼", py: "yú", emoji: "🐟", word: "渔获" },
      { char: "一", py: "yī", emoji: "1️⃣", word: "一天" },
    ],
    chars: ["一", "大", "小", "人"],
    seq: {
      "一": "横",
      "大": "横 → 撇 → 捺",
      "小": "竖钩 → 撇 → 点",
      "人": "撇 → 捺",
    },
    speak: ["毕业不是终点，是新的开始。", "带着耐心坚持，去更大的湖边吧。", "小钓手，你已经很棒啦！"],
    quiz: [
      { p: "三十天里你学会了什么？", opt: [ {e:"🎓",t:"耐心坚持感恩安全",r:1}, {e:"🍔",t:"吃汉堡"}, {e:"📱",t:"刷手机"} ] },
      { p: "教练说毕业是什么？", opt: [ {e:"🚩",t:"新的开始",r:1}, {e:"🛑",t:"终点站"}, {e:"😴",t:"结束睡觉"} ] },
      { p: "拿到证书应该怎么做？", opt: [ {e:"🚶",t:"继续练习",r:1}, {e:"🛋️",t:"躺着不练了"}, {e:"🎉",t:"再也不拿鱼竿"} ] },
    ],
    craft: '全家一起画一张大大的"毕业锦旗"，把30天里孩子学会的每一个词写成小旗帜挂上去，仪式感拉满（总结与自信）。',
    parent: '郑重地举行一次"颁证仪式"，把证书贴在显眼处。和孩子回顾这30天最大的3个变化，肯定每一份坚持。',
  },
};

// ===================== 句式小屋：连词小课堂（8岁写作衔接词） =====================
// opts 三选一，[word, isRight]；pre + 空 + post 组成完整句子
const SENT = {
  1: { name: "承接·于是", tip: "「于是」连接前后两件事：前面的准备好了，后面的就发生了。",
    sents: [
      { pre: "姜太公坐在渭水边，", right: "于是", post: "大家都围过来看他的直钩。", opts: [["但是",0],["于是",1],["如果",0]] },
      { pre: "周王听说姜太公很厉害，", right: "于是", post: "亲自来请他出山。", opts: [["于是",1],["可是",0],["所以",0]] },
    ] },
  2: { name: "因果·因为……所以……", tip: "「因为」说原因，「所以」说结果，道理讲得明明白白。",
    sents: [
      { pre: "因为老渔夫心很善，", right: "所以", post: "他把金鱼放回了大海。", opts: [["但是",0],["所以",1],["而且",0]] },
      { pre: "", right: "因为", post: "要个不停，所以快乐反而越来越少。", opts: [["于是",0],["因为",1],["只要",0]] },
    ] },
  3: { name: "转折·虽然……但是……", tip: "「虽然」先承认不容易，「但是」一转，说出坚定的信心。",
    sents: [
      { pre: "", right: "虽然", post: "小鲤鱼一次次落水，但是它一点也不灰心。", opts: [["虽然",1],["因为",0],["如果",0]] },
      { pre: "虽然失败了五十六次，", right: "但是", post: "它越跳越有劲。", opts: [["并且",0],["就",0],["但是",1]] },
    ] },
  4: { name: "转折·可是", tip: "「可是」轻轻一转折，话的意思就换了方向。",
    sents: [
      { pre: "小鱼急着要一瓢水，", right: "可是", post: "庄子却说要等大河的水。", opts: [["于是",0],["因为",0],["可是",1]] },
      { pre: "庄子答应得很爽快，", right: "可是", post: "远水救不了近渴。", opts: [["所以",0],["可是",1],["而且",0]] },
    ] },
  5: { name: "假设·否则", tip: "「否则」等于说《如果不这样做》——提醒我们别让坏结果发生。",
    sents: [
      { pre: "猎人得给鸟儿留条生路，", right: "否则", post: "所有飞鸟都会被困住。", opts: [["于是",0],["然后",0],["否则",1]] },
      { pre: "做人要宽厚一些，", right: "否则", post: "朋友会越处越少。", opts: [["因为",0],["只要",0],["否则",1]] },
    ] },
  6: { name: "因果·因为……所以……", tip: "讲清原因和结果，别人才能听明白你的道理。",
    sents: [
      { pre: "因为鱼靠鳃在水里呼吸，", right: "所以", post: "它一步也离不开水。", opts: [["但是",0],["所以",1],["如果",0]] },
      { pre: "", right: "因为", post: "鳃丝离开水会粘在一起，所以小鱼才会难受。", opts: [["因为",1],["而且",0],["于是",0]] },
    ] },
  7: { name: "顺序·先……然后……", tip: "讲故事和做任务，用「先……然后……」把顺序排得清清楚楚。",
    sents: [
      { pre: "先对着光举起鱼鳞，", right: "然后", post: "一圈一圈数它的年龄。", opts: [["所以",0],["可是",0],["然后",1]] },
      { pre: "先仔细观察鳞纹，", right: "然后", post: "把发现画进日记本。", opts: [["但是",0],["然后",1],["就",0]] },
    ] },
  8: { name: "因果·因为……所以……", tip: "说原因再下结论，话就有根有据。",
    sents: [
      { pre: "因为钩尖不够锋利，", right: "所以", post: "大鱼一挣就脱了钩。", opts: [["于是",0],["虽然",0],["所以",1]] },
      { pre: "因为穿饵露出了钩尖，", right: "所以", post: "鱼一下子就发现了危险。", opts: [["然后",0],["可是",0],["所以",1]] },
    ] },
  9: { name: "假设·如果……就……", tip: "「如果」是假设，「就」是假设带来的结果。",
    sents: [
      { pre: "如果浮漂猛地扎进水里，", right: "就", post: "那是有鱼咬钩了。", opts: [["才",0],["于是",0],["就",1]] },
      { pre: "如果浮漂只是轻轻点头，", right: "就", post: "先按住耐心，等鱼咬牢。", opts: [["就",1],["所以",0],["但是",0]] },
    ] },
  10: { name: "条件·只要……就……", tip: "「只要」给条件，「就」给结果——条件做到了，结果就会来。",
    sents: [
      { pre: "只要天天练习打结，", right: "就", post: "手法一定会又稳又快。", opts: [["才",0],["于是",0],["就",1]] },
      { pre: "只要用心多练基本功，", right: "就", post: "再难的结也难不倒你。", opts: [["但是",0],["就",1],["所以",0]] },
    ] },
  11: { name: "承接·于是", tip: "两件事先后接着发生，用「于是」把它们串起来。",
    sents: [
      { pre: "月亮悄悄升起，", right: "于是", post: "大海涨起了潮。", opts: [["因为",0],["于是",1],["如果",0]] },
      { pre: "太阳慢慢落下，", right: "于是", post: "晚风把鱼线吹得晃呀晃。", opts: [["然后",0],["于是",1],["可是",0]] },
    ] },
  12: { name: "转折·虽然……但是……", tip: "先承认一样，再说另一样不同——「虽然……但是……」最常这样用。",
    sents: [
      { pre: "虽然鲫鱼和带鱼都会游泳，", right: "但是", post: "它们一个住淡水，一个住咸水。", opts: [["所以",0],["并且",0],["但是",1]] },
      { pre: "", right: "虽然", post: "海水鱼和淡水鱼都是鱼，但是它们不能随便换家。", opts: [["虽然",1],["因为",0],["如果",0]] },
    ] },
  13: { name: "目的·为了", tip: "「为了」说出做这件事的目的，行动就更让人佩服。",
    sents: [
      { pre: "大马哈鱼逆着水流拼命游，", right: "为了", post: "回到出生的那条河。", opts: [["所以",0],["为了",1],["于是",0]] },
      { pre: "它冲过瀑布和乱石，", right: "为了", post: "完成回家的心愿。", opts: [["如果",0],["可是",0],["为了",1]] },
    ] },
  14: { name: "递进·越……越……", tip: "「越……越……」表示一边变强，另一边也一起变强。",
    sents: [
      { pre: "鳟鱼越是迎着困难，", right: "就越", post: "有力量。", opts: [["于是",0],["就越",1],["但是",0]] },
      { pre: "遇到的困难越难，", right: "就", post: "战胜后的收获越大。", opts: [["才",0],["越",0],["就",1]] },
    ] },
  15: { name: "条件·无论……都……", tip: "「无论……都……」表示不管什么情况，结果都不变。",
    sents: [
      { pre: "", right: "无论", post: "谁想欺负小黑鱼，黑鱼妈妈都会冲上去。", opts: [["只要",0],["如果",0],["无论",1]] },
      { pre: "无论白天还是黑夜，", right: "都", post: "妈妈的爱从不缺席。", opts: [["就",0],["才",0],["都",1]] },
    ] },
  16: { name: "并列·有的……有的……", tip: "「有的……有的……」把不同的人或事一一说出来。",
    sents: [
      { pre: "", right: "有的", post: "鲫鱼在水面吃虫，有的鲤鱼在泥里翻食。", opts: [["有时",0],["很多",0],["有的",1]] },
      { pre: "鱼塘里的伙伴各有本领，", right: "有的", post: "负责浅水，有的负责深泥塘。", opts: [["一旦",0],["因为",0],["有的",1]] },
    ] },
  17: { name: "递进·不仅……还……", tip: "「不仅……还……」一层说不够，再来一层，越说越深。",
    sents: [
      { pre: "鲈鱼不仅游得快，", right: "还", post: "让古人写下诗来夸它。", opts: [["就",0],["才",0],["还",1]] },
      { pre: "", right: "不仅", post: "大人喜欢鲈鱼的鲜美，孩子们也爱听它的故事。", opts: [["因为",0],["虽然",0],["不仅",1]] },
    ] },
  18: { name: "因果·因为……所以……", tip: "把分工的原因讲明白，谁听了都服气。",
    sents: [
      { pre: "因为清道夫专吃青苔，", right: "所以", post: "鱼缸被它擦得亮晶晶。", opts: [["但是",0],["于是",0],["所以",1]] },
      { pre: "因为草鱼爱吃水草，", right: "所以", post: "池塘不会被水草堵住。", opts: [["然后",0],["可是",0],["所以",1]] },
    ] },
  19: { name: "假设·如果……就……", tip: "像小气象员一样，用「如果……就……」判断天气。",
    sents: [
      { pre: "如果天边涌起黑云，", right: "就", post: "赶紧收竿回家。", opts: [["才",0],["只有",0],["就",1]] },
      { pre: "如果刮起了大风，", right: "就", post: "鱼躲进水底不出来。", opts: [["于是",0],["但是",0],["就",1]] },
    ] },
  20: { name: "条件·无论……都……", tip: "安全守则用「无论……都……」说出，最有力量。",
    sents: [
      { pre: "无论河边多好玩，", right: "都", post: "不能一个人下水。", opts: [["就",0],["所以",0],["都",1]] },
      { pre: "", right: "无论", post: "水看起来多浅，我们都要先叫大人来。", opts: [["如果",0],["只有",0],["无论",1]] },
    ] },
  21: { name: "条件·只有……才……", tip: "「只有……才……」表示先做到这一步，才有后面的结果。",
    sents: [
      { pre: "只有把小鱼放回水里，", right: "才", post: "明天才有更多鱼儿长大。", opts: [["就",0],["于是",0],["才",1]] },
      { pre: "", right: "只有", post: "人人都爱护水域，鱼儿才能越来越多。", opts: [["只要",0],["虽然",0],["只有",1]] },
    ] },
  22: { name: "并列·既……又……", tip: "「既……又……」把两件好事同时做到，说话很周到。",
    sents: [
      { pre: "守公约既可以护鱼，", right: "又", post: "可以护住钓鱼的人。", opts: [["就",0],["而",0],["又",1]] },
      { pre: "大家既轻声说话，", right: "又", post: "主动带走自己的垃圾。", opts: [["和",0],["便",0],["又",1]] },
    ] },
  23: { name: "转折·虽然……但是……", tip: "先说出意外的点，再用「但是」把话补完整。",
    sents: [
      { pre: "虽然鱼没有眼皮，", right: "但是", post: "它们也会安静睡个好觉。", opts: [["所以",0],["然后",0],["但是",1]] },
      { pre: "", right: "虽然", post: "鱼老是睁着眼睛，但是它们真的需要休息。", opts: [["因为",0],["如果",0],["虽然",1]] },
    ] },
  24: { name: "并列·有时……有时……", tip: "「有时……有时……」把不一样的情景都讲出来，特别接地气。",
    sents: [
      { pre: "鱼跳出水面，", right: "有时", post: "是在躲大鱼，有时是在吃飞虫。", opts: [["当然",0],["然后",0],["有时",1]] },
      { pre: "鱼跃出水面，", right: "有时", post: "是玩得高兴，有时是想透气。", opts: [["终于",0],["突然",0],["有时",1]] },
    ] },
  25: { name: "递进·不仅……还……", tip: "记日记用「不仅……还……」，越记越详细。",
    sents: [
      { pre: "小钓手不仅写上日期，", right: "还", post: "画下今天钓的鱼。", opts: [["也",0],["就",0],["还",1]] },
      { pre: "", right: "不仅", post: "日记记下天气，还把新学的动作也记了下来。", opts: [["既然",0],["尽管",0],["不仅",1]] },
    ] },
  26: { name: "递进·越……越……", tip: "「越……越……」用在记录和比较里，特别提神。",
    sents: [
      { pre: "记录得越多，", right: "就越", post: "能看清自己进步多少。", opts: [["才",0],["但是",0],["就越",1]] },
      { pre: "数字记得越清楚，", right: "就越", post: "下次比较越方便。", opts: [["只",0],["再",0],["就越",1]] },
    ] },
  27: { name: "递进·不但……而且……", tip: "「不但……而且……」一层接一层，把本领说得越来越强。",
    sents: [
      { pre: "这根钓线不但细，", right: "而且", post: "还特别结实，能吊起大鱼。", opts: [["但是",0],["于是",0],["而且",1]] },
      { pre: "科学家不但研究鱼线，", right: "而且", post: "还造出了结实的桥索。", opts: [["如果",0],["因为",0],["而且",1]] },
    ] },
  28: { name: "承接·一边……一边……", tip: "「一边……一边……」表示两件事同时进行。",
    sents: [
      { pre: "爷爷一边念叨谚语，", right: "一边", post: "一边教我认云识天气。", opts: [["然后",0],["就",0],["一边",1]] },
      { pre: "我们一边钓鱼，", right: "一边", post: "一边唱着节气歌。", opts: [["立刻",0],["终于",0],["一边",1]] },
    ] },
  29: { name: "并列·有的……有的……", tip: "把每个人的分享都说进去，场面就更热闹。",
    sents: [
      { pre: "大家围成一圈，", right: "有的", post: "讲第一次上鱼的心跳，有的讲放流的不舍。", opts: [["许多",0],["忽然",0],["有的",1]] },
      { pre: "小钓手们讲起故事，", right: "有的", post: "笑得眼睛弯弯，有的认真做着笔记。", opts: [["一个",0],["刚刚",0],["有的",1]] },
    ] },
  30: { name: "条件·只要……就……", tip: "毕业了，也继续用「只要……就……」给自己打气吧。",
    sents: [
      { pre: "只要每天坚持练习，", right: "就", post: "一定会有满满的收获。", opts: [["才",0],["于是",0],["就",1]] },
      { pre: "", right: "只要", post: "记住耐心和感恩，走到哪儿都是好钓手。", opts: [["如果",0],["为了",0],["只要",1]] },
    ] },
};
Object.keys(SENT).forEach(n => { DAY_DATA[n].sentence = SENT[n]; });